import type { Folder, Work } from "./types";

export const DEMO_USER = {
  nickname: "演示账号",
  douyinId: "archive_demo",
};

export const FOLDERS: Folder[] = [
  { id: "default", name: "收藏", isDefault: true },
  { id: "cos", name: "COS", isDefault: false },
  { id: "photo", name: "摄影参考", isDefault: false },
];

const now = Date.UTC(2026, 8, 5);

export const WORKS: Work[] = [
  {
    id: "74819211001",
    title: "宫廷绣袍打版参考 侧光",
    authorName: "针线馆",
    douyinId: "zhendxianguan",
    caption: "绣金线的袍子侧光最好看 #cos #古风 #打版",
    hashtags: ["cos", "古风", "打版"],
    userTags: ["要复刻"],
    folderId: "cos",
    alsoInFolderIds: [],
    kind: "album",
    videoStatus: "none",
    status: "downloaded",
    collectedAt: now - 1 * 86400000,
    coverUrl: "/covers/c1.jpg",
    videos: [],
    images: [
      { id: "a1", url: "/covers/c1.jpg" },
      { id: "a2", url: "/covers/c9.jpg" },
      { id: "a3", url: "/covers/c6.jpg" },
    ],
  },
  {
    id: "74819211002",
    title: "旁轴开盖与胶卷",
    authorName: "暗盒实验室",
    douyinId: "darkboxlab",
    caption: "把后盖打开才能看清片窗 #摄影 #胶片 #器材",
    hashtags: ["摄影", "胶片", "器材"],
    userTags: [],
    folderId: "photo",
    alsoInFolderIds: [],
    kind: "album",
    videoStatus: "none",
    status: "new",
    collectedAt: now - 0.3 * 86400000,
    coverUrl: "/covers/c2.jpg",
    videos: [],
    images: [
      { id: "b1", url: "/covers/c2.jpg" },
      { id: "b2", url: "/covers/c10.jpg" },
    ],
  },
  {
    id: "74819211003",
    title: "雨夜巷口 灯下",
    authorName: "夜行记",
    douyinId: "nightwalk_cn",
    caption: "湿地面把灯全接住了 #街拍 #夜景",
    hashtags: ["街拍", "夜景"],
    userTags: [],
    folderId: "default",
    alsoInFolderIds: [],
    kind: "album",
    videoStatus: "none",
    status: "stale",
    collectedAt: now - 12 * 86400000,
    coverUrl: "/covers/c3.jpg",
    videos: [],
    images: [
      { id: "c1", url: "/covers/c3.jpg" },
      { id: "c2", url: "/covers/c11.jpg" },
    ],
  },
  {
    id: "74819211004",
    title: "美术馆一线光",
    authorName: "混凝土日记",
    douyinId: "beton_notes",
    caption: "只有一道光的时候空间才干净 #建筑 #空间",
    hashtags: ["建筑", "空间"],
    userTags: [],
    folderId: "photo",
    alsoInFolderIds: [],
    kind: "album",
    videoStatus: "none",
    status: "no-origin",
    collectedAt: now - 2 * 86400000,
    coverUrl: "/covers/c4.jpg",
    videos: [],
    images: [{ id: "d1", url: "/covers/c4.jpg" }],
  },
  {
    id: "74819211005",
    title: "白牡丹与深麻",
    authorName: "桌面博物",
    douyinId: "tablemuse",
    caption: "花比花瓶更安静 #静物 #花卉",
    hashtags: ["静物", "花卉"],
    userTags: ["桌面"],
    folderId: "default",
    alsoInFolderIds: [],
    kind: "album",
    videoStatus: "none",
    status: "downloaded",
    collectedAt: now - 4 * 86400000,
    coverUrl: "/covers/c5.jpg",
    videos: [],
    images: [
      { id: "e1", url: "/covers/c5.jpg" },
      { id: "e2", url: "/covers/c12.jpg" },
    ],
  },
  {
    id: "74819211006",
    title: "后台衣架 单点光",
    authorName: "针线馆",
    douyinId: "zhendxianguan",
    caption: "静图和无水印原视频都要 #cos #舞台",
    hashtags: ["cos", "舞台"],
    userTags: [],
    folderId: "cos",
    alsoInFolderIds: [],
    kind: "video",
    videoStatus: "pending",
    videoUrl: "/videos/v1.mp4",
    status: "new",
    collectedAt: now - 0.8 * 86400000,
    coverUrl: "/covers/v1.jpg",
    videos: [{ id: "f-v1", url: "/videos/v1.mp4" }],
    images: [{ id: "f1", url: "/covers/v1.jpg" }],
  },
  {
    id: "74819211007",
    title: "雾松清晨",
    authorName: "海拔笔记",
    douyinId: "alt_notes",
    caption: "山还没醒 #风景",
    hashtags: ["风景"],
    userTags: [],
    folderId: "default",
    alsoInFolderIds: [],
    kind: "video",
    videoStatus: "saved",
    videoUrl: "/videos/c7.mp4",
    status: "downloaded",
    collectedAt: now - 6 * 86400000,
    coverUrl: "/covers/c7.jpg",
    videos: [{ id: "g-v1", url: "/videos/c7.mp4" }],
    images: [{ id: "g1", url: "/covers/c7.jpg" }],
  },
  {
    id: "74819211008",
    title: "茶席蒸汽",
    authorName: "桌面博物",
    douyinId: "tablemuse",
    caption: "蒸汽比茶更上镜 #静物 #茶",
    hashtags: ["静物", "茶"],
    userTags: [],
    folderId: "photo",
    alsoInFolderIds: ["default"],
    kind: "album",
    videoStatus: "none",
    status: "new",
    collectedAt: now - 0.1 * 86400000,
    coverUrl: "/covers/c8.jpg",
    videos: [],
    images: [{ id: "h1", url: "/covers/c8.jpg" }],
  },
  {
    id: "74819211009",
    title: "绣金特写",
    authorName: "针线馆",
    douyinId: "zhendxianguan",
    caption: "金线要侧光才立得住 #cos #刺绣",
    hashtags: ["cos", "刺绣"],
    userTags: [],
    folderId: "cos",
    alsoInFolderIds: [],
    kind: "album",
    videoStatus: "none",
    status: "new",
    collectedAt: now - 0.05 * 86400000,
    coverUrl: "/covers/c9.jpg",
    videos: [],
    images: [
      { id: "i1", url: "/covers/c9.jpg" },
      { id: "i2", url: "/covers/c1.jpg" },
    ],
  },
  {
    id: "74819211011",
    title: "雾中栈道",
    authorName: "海拔笔记",
    douyinId: "alt_notes",
    caption: "静图有，原视频没拿到 #风景",
    hashtags: ["风景"],
    userTags: [],
    folderId: "default",
    alsoInFolderIds: [],
    kind: "video",
    videoStatus: "missing",
    status: "downloaded",
    collectedAt: now - 3 * 86400000,
    coverUrl: "/covers/v2.jpg",
    videos: [],
    images: [{ id: "k1", url: "/covers/v2.jpg" }],
  },
  {
    id: "74819211012",
    title: "窗边试妆台",
    authorName: "针线馆",
    douyinId: "zhendxianguan",
    caption: "开场前十分钟 #cos #妆造",
    hashtags: ["cos", "妆造"],
    userTags: ["要复刻"],
    folderId: "cos",
    alsoInFolderIds: [],
    kind: "mixed",
    videoStatus: "saved",
    videoUrl: "/videos/v6.mp4",
    status: "downloaded",
    collectedAt: now - 2.2 * 86400000,
    coverUrl: "/covers/v6.jpg",
    videos: [{ id: "l-v1", url: "/videos/v6.mp4" }],
    images: [
      { id: "l1", url: "/covers/v6.jpg" },
      { id: "l2", url: "/covers/c1.jpg" },
    ],
  },
  {
    id: "74819211013",
    title: "雨棚车灯",
    authorName: "夜行记",
    douyinId: "nightwalk_cn",
    caption: "等车的时候地面比天更亮 #街拍 #夜景",
    hashtags: ["街拍", "夜景"],
    userTags: [],
    folderId: "default",
    alsoInFolderIds: [],
    kind: "video",
    videoStatus: "saved",
    videoUrl: "/videos/v3.mp4",
    status: "downloaded",
    collectedAt: now - 1.4 * 86400000,
    coverUrl: "/covers/v3.jpg",
    videos: [{ id: "m-v1", url: "/videos/v3.mp4" }],
    images: [{ id: "m1", url: "/covers/v3.jpg" }],
  },
  {
    id: "74819211014",
    title: "陶碗拉坯",
    authorName: "桌面博物",
    douyinId: "tablemuse",
    caption: "水比泥更上镜 #静物 #手作",
    hashtags: ["静物", "手作"],
    userTags: ["桌面"],
    folderId: "photo",
    alsoInFolderIds: ["default"],
    kind: "mixed",
    videoStatus: "saved",
    videoUrl: "/videos/v4.mp4",
    status: "downloaded",
    collectedAt: now - 0.6 * 86400000,
    coverUrl: "/covers/v4.jpg",
    videos: [{ id: "n-v1", url: "/videos/v4.mp4" }],
    images: [
      { id: "n1", url: "/covers/v4.jpg" },
      { id: "n2", url: "/covers/c5.jpg" },
    ],
  },
  {
    id: "74819211015",
    title: "山脊云海",
    authorName: "海拔笔记",
    douyinId: "alt_notes",
    caption: "等了三天的日出 #风景",
    hashtags: ["风景"],
    userTags: [],
    folderId: "default",
    alsoInFolderIds: [],
    kind: "video",
    videoStatus: "pending",
    videoUrl: "/videos/v5.mp4",
    status: "new",
    collectedAt: now - 0.2 * 86400000,
    coverUrl: "/covers/v5.jpg",
    videos: [{ id: "o-v1", url: "/videos/v5.mp4" }],
    images: [{ id: "o1", url: "/covers/v5.jpg" }],
  },
  {
    id: "74819211016",
    title: "林线雾带",
    authorName: "海拔笔记",
    douyinId: "alt_notes",
    caption: "源已失效，本地静图和视频还在 #风景",
    hashtags: ["风景"],
    userTags: [],
    folderId: "photo",
    alsoInFolderIds: [],
    kind: "video",
    videoStatus: "saved",
    videoUrl: "/videos/c7.mp4",
    status: "stale",
    collectedAt: now - 9 * 86400000,
    coverUrl: "/covers/c7.jpg",
    videos: [{ id: "p-v1", url: "/videos/c7.mp4" }],
    images: [{ id: "p1", url: "/covers/c7.jpg" }],
  },
  {
    id: "74819211017",
    title: "试妆两段",
    authorName: "针线馆",
    douyinId: "zhendxianguan",
    caption: "一段台前一段后台 #cos #妆造",
    hashtags: ["cos", "妆造"],
    userTags: ["要复刻"],
    folderId: "cos",
    alsoInFolderIds: [],
    kind: "video",
    videoStatus: "saved",
    videoUrl: "/videos/v6.mp4",
    status: "downloaded",
    collectedAt: now - 0.4 * 86400000,
    coverUrl: "/covers/v6.jpg",
    videos: [
      { id: "q-v1", url: "/videos/v6.mp4" },
      { id: "q-v2", url: "/videos/v1.mp4" },
    ],
    images: [
      { id: "q1", url: "/covers/v6.jpg" },
      { id: "q2", url: "/covers/v1.jpg" },
    ],
  },
  {
    id: "74819211018",
    title: "拉坯与成品",
    authorName: "桌面博物",
    douyinId: "tablemuse",
    caption: "过程视频和静物图都在 #静物 #手作",
    hashtags: ["静物", "手作"],
    userTags: ["桌面"],
    folderId: "photo",
    alsoInFolderIds: ["default"],
    kind: "mixed",
    videoStatus: "saved",
    videoUrl: "/videos/v4.mp4",
    status: "downloaded",
    collectedAt: now - 0.15 * 86400000,
    coverUrl: "/covers/v4.jpg",
    videos: [
      { id: "r-v1", url: "/videos/v4.mp4" },
      { id: "r-v2", url: "/videos/v3.mp4" },
    ],
    images: [
      { id: "r1", url: "/covers/v4.jpg" },
      { id: "r2", url: "/covers/c5.jpg" },
      { id: "r3", url: "/covers/c8.jpg" },
    ],
  },
];

export const PENDING_REFRESH_WORK: Work = {
  id: "74819211010",
  title: "灯下单车",
  authorName: "夜行记",
  douyinId: "nightwalk_cn",
  caption: "新收藏的一张 #街拍",
  hashtags: ["街拍"],
  userTags: [],
  folderId: "default",
  alsoInFolderIds: [],
  kind: "album",
  videoStatus: "none",
  status: "new",
  collectedAt: now + 3600000,
  coverUrl: "/covers/c11.jpg",
  videos: [],
  images: [{ id: "j1", url: "/covers/c11.jpg" }],
};

export const DEMO_WORK_IDS = new Set([...WORKS.map((w) => w.id), PENDING_REFRESH_WORK.id]);

export function isDemoWork(work: { id: string; coverUrl?: string }) {
  if (DEMO_WORK_IDS.has(work.id)) return true;
  const cover = work.coverUrl || "";
  return cover.startsWith("/covers/") || cover.startsWith("/videos/");
}
