import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {verifyAccountIdentity} from '../electron/account-identity.mjs';import {Collector} from '../electron/account-collector.mjs';import {Store} from '../electron/store.mjs';
const auth=(cookie='new-cookie')=>({userAgent:'Fixture/1',source:'popup',cookies:[{name:'sessionid',value:'not-real',domain:'.douyin.com'},{name:'uid_tt',value:cookie,domain:'.douyin.com'}]});
async function fixture(t,verifyIdentity){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-account-identity-'));const store=await Store.open(path.join(dir,'library.sqlite'),path.join(dir,'media'));t.after(()=>{store.close();assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true});});let saved=null,cleared=0;const profile={clearStorageData:async()=>{cleared++;},setUserAgent(){},cookies:{set:async()=>{}}};const collector=new Collector(store,()=>{},{profile,browser:{on(){}},vault:{load:()=>null,save:v=>{saved=v;}},verifyIdentity});await collector.ready;return {store,collector,get saved(){return saved;},get cleared(){return cleared;}};}
test('authenticated self identity preserves large IDs and verifies legacy folder ownership',async()=>{
 const calls=[];const profile={fetch:async url=>{calls.push(new URL(url).pathname);return new Response(calls.length===1?'{"status_code":0,"user":{"uid":9007199254740993001,"nickname":"fixture"}}':JSON.stringify({status_code:0,collects_list:[{collects_id_str:'99'}],has_more:0}));}};
 const result=await verifyAccountIdentity(profile,'Fixture',{legacyCollections:['99']});assert.equal(result.uid,'9007199254740993001');assert.equal(result.ownsLegacyCollection,true);assert.deepEqual(calls,['/aweme/v1/web/user/profile/self/','/aweme/v1/web/collects/list/']);
});
test('self identity refuses anonymous or failed profile responses',async()=>{for(const body of [{status_code:0,user:{uid:'0'}},{status_code:8,user:{uid:'123'}},{aweme_detail:{author:{uid:'123'}}}])await assert.rejects(verifyAccountIdentity({fetch:async()=>new Response(JSON.stringify(body))},'Fixture'));});
test('same verified account accepts a changed Cookie without replacing the account',async t=>{const f=await fixture(t,async()=>({uid:'123',nickname:'fixture'}));f.store.setSetting('browserAccountKey','uid:123');await f.collector.applyAuth(auth());assert.equal(f.collector.status.connected,true);assert.equal(f.store.getSetting('browserAccountKey'),'uid:123');assert.equal(f.saved.identity.uid,'123');});
test('legacy binding migrates only after verifying ownership of a saved collection',async t=>{let requested;const f=await fixture(t,async(_p,_ua,options)=>{requested=options.legacyCollections;return {uid:'123',nickname:'fixture',ownsLegacyCollection:true};});f.store.setSetting('browserAccountKey','a'.repeat(64));f.store.discoverCollections([{collects_id:'99',collects_name:'fixture'}]);f.store.setAdded(['99']);await f.collector.applyAuth(auth());assert.deepEqual(requested,['99']);assert.equal(f.store.getSetting('browserAccountKey'),'uid:123');assert.equal(f.collector.status.connected,true);});
test('different verified account and unproven legacy account cannot overwrite existing credentials or binding',async t=>{for(const bound of ['uid:456','a'.repeat(64)]){const f=await fixture(t,async()=>({uid:'123',nickname:'fixture',ownsLegacyCollection:false}));f.store.setSetting('browserAccountKey',bound);await assert.rejects(f.collector.applyAuth(auth()),e=>['ACCOUNT_MISMATCH','ACCOUNT_UNVERIFIED'].includes(e.code));assert.equal(f.saved,null);assert.equal(f.store.getSetting('browserAccountKey'),bound);assert.equal(f.collector.status.connected,false);assert.ok(f.cleared>=2);}});
test('NAS not ready rejects login before credentials are saved',async t=>{let verified=false;const f=await fixture(t,async()=>{verified=true;return {uid:'123'};});f.store.backup={assertWritable(){throw new Error('NAS not ready');},canWrite:()=>false,localKey:()=>true,changed(){}};await assert.rejects(f.collector.applyAuth(auth()),/NAS not ready/);assert.equal(f.saved,null);assert.equal(verified,false);});
test('verified saved identity restores locally without a network request',async t=>{const f=await fixture(t,async()=>{throw new Error('unexpected network');});f.store.setSetting('browserAccountKey','uid:123');const saved=auth();saved.identity={uid:'123',nickname:'fixture'};await f.collector.applyAuth(saved,false);assert.equal(f.collector.status.connected,true);assert.equal(f.saved,null);});
test('cancelling identity verification never saves the candidate login',async t=>{const controller=new AbortController();const f=await fixture(t,async()=>{controller.abort();return {uid:'123'};});await assert.rejects(f.collector.applyAuth(auth(),true,{signal:controller.signal}),e=>e.name==='AbortError');assert.equal(f.saved,null);assert.equal(f.store.getSetting('browserAccountKey'),null);assert.equal(f.collector.status.connected,false);});
