import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {randomBytes,randomUUID,X509Certificate} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {createBackupServer} from '../backup-server/server.mjs';import {BackupClient} from '../electron/backup-client.mjs';import {BackupTransport} from '../electron/backup-transport.mjs';import {Store} from '../electron/store.mjs';import {sha256} from '../shared/backup-protocol.mjs';
import {DownloadQueue} from '../electron/downloads.mjs';
const vault={seal:s=>Buffer.from(s).toString('base64'),open:s=>Buffer.from(s,'base64').toString()};
const previewPNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==','base64');
function readOnlyWork(store,id='456'){store.upsertWork({aweme_id:id,desc:'read without downloading',author:{nickname:'fixture'},video:{cover:{url_list:['https://p3.douyinpic.com/preview.png']},play_addr:{url_list:[]}}});store.ingestMembers('__all__',[id],true);store.save();}
async function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-backup-test-')),token=randomBytes(32).toString('hex'),service=createBackupServer({dataDir:path.join(dir,'server'),token,allowInsecureLoopback:true});const address=await service.listen();const url='http://127.0.0.1:'+address.port;const clients=[];
 t.after(async()=>{for(const c of clients){await c.close();c.store.close();}await service.close().catch(()=>{});assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:200});});
 const client=async(name,seed=false)=>{const profile=path.join(dir,name),store=await Store.open(path.join(profile,'library.sqlite'),path.join(profile,'media'));if(seed){store.upsertWork({aweme_id:'123',desc:'backup fixture',author:{nickname:'author'},video:{play_addr:{url_list:[]}}});store.ingestMembers('__all__',['123'],true);const where=store.destination('123').dir;fs.mkdirSync(where,{recursive:true});fs.writeFileSync(path.join(where,'video.mp4'),'media-fixture');store.put('downloads','123',{id:'123',path:where,state:'complete',collectionId:'__all__',assets:[{key:'video',file:'video.mp4',kind:'video',size:13}]});store.save();}
  const c=new BackupClient(store,profile,{vault,heartbeatMs:60000});clients.push(c);await c.configure({url,token,deviceName:name,intervalMinutes:60});return c;};return {dir,token,service,url,client};
}
test('backup mode starts read-only and never requires a NAS path for local storage',async t=>{const f=await fixture(t);const s=await Store.open(path.join(f.dir,'alone.sqlite'),path.join(f.dir,'alone-media'));const c=new BackupClient(s,path.join(f.dir,'alone'),{vault});assert.equal(c.status.writable,false);assert.throws(()=>s.upsertWork({aweme_id:'1'}));assert.deepEqual(s.snapshot().works,[]);await c.close();s.close();});
test('read-only work previews survive a completely fresh PC without login and never count as downloaded media',async t=>{
 const f=await fixture(t),a=await f.client('PC-A');readOnlyWork(a.store);let fetches=0;a.fetchCover=async()=>{fetches++;return new Response(previewPNG,{headers:{'content-type':'image/png'}});};await a.sync();assert.equal(fetches,1);assert.equal(a.status.pendingCovers,0);assert.equal(a.status.phase,'synced');assert.equal(a.store.all('downloads').length,0);assert.equal(a.store.all('backup_downloads').length,0);assert.ok(a.store.work('456').backupCover);
 await a.release();const b=await f.client('PC-CLEAN');b.fetchCover=async()=>{throw Error('must not contact Douyin');};assert.equal(b.store.all('downloads').length,0);assert.equal(b.store.all('backup_downloads').length,0);const file=await b.covers.get('456');assert.deepEqual(fs.readFileSync(file),previewPNG);assert.equal(b.store.snapshot().works[0].backedUp,false);assert.equal(b.store.snapshot().works[0].downloaded,false);assert.equal(b.status.pending,false);await b.sync();assert.equal(f.service.status().revision,1);
});
test('legacy local cover cache is included in backup without contacting Douyin',async t=>{const f=await fixture(t),a=await f.client('PC-A');readOnlyWork(a.store);fs.mkdirSync(path.join(a.profile,'covers'));fs.writeFileSync(path.join(a.profile,'covers','456.jpg'),previewPNG);a.fetchCover=async()=>{throw Error('must use cached preview');};await a.sync();const b=await f.client('PC-B');assert.deepEqual(fs.readFileSync(await b.covers.get('456')),previewPNG);});
test('unavailable or invalid previews do not block records and do not claim full synchronization',async t=>{
 const f=await fixture(t),a=await f.client('PC-A');readOnlyWork(a.store);a.fetchCover=async()=>new Response('<html>not an image</html>',{headers:{'content-type':'image/jpeg'}});await a.sync();assert.equal(f.service.status().revision,1);assert.equal(a.status.phase,'coversPending');assert.equal(a.status.pendingCovers,1);assert.equal(a.status.pending,true);assert.equal(a.store.work('456').backupCover,undefined);
 a.fetchCover=async()=>new Response(previewPNG,{headers:{'content-type':'image/png'}});await a.sync();assert.equal(a.status.phase,'synced');assert.equal(a.status.pendingCovers,0);assert.equal(f.service.status().revision,2);
});
test('cover commit acknowledgement preserves concurrent edits and a lost response recovers the uploaded preview',async t=>{
 const f=await fixture(t),a=await f.client('PC-A');readOnlyWork(a.store);a.fetchCover=async()=>new Response(previewPNG,{headers:{'content-type':'image/png'}});const upload=a.transport.upload.bind(a.transport);a.transport.upload=async(...args)=>{a.store.put('works','456',{...a.store.work('456'),name:'edited during upload'});return upload(...args);};const json=a.transport.json.bind(a.transport);let drop=true;a.transport.json=async(...args)=>{const result=await json(...args);if(drop&&args[1]==='/v1/commit'){drop=false;throw Error('lost preview receipt');}return result;};await assert.rejects(a.sync(),/lost preview receipt/);assert.ok(a.meta.pendingCommit);await a.check();assert.equal(a.store.work('456').name,'edited during upload');assert.ok(a.store.work('456').backupCover);assert.equal(a.status.pending,true);assert.equal(f.service.status().revision,1);await a.sync();assert.equal(a.status.phase,'synced');
});
test('fresh PC retains independent folder ranks and confirmed total order despite out-of-order cover fetching',async t=>{
 const f=await fixture(t),a=await f.client('PC-A');a.store.discoverCollections([{collects_id:'9',collects_name:'A'},{collects_id:'6',collects_name:'B'}]);a.store.setAdded(['9','6']);
 for(const id of ['10','20','40','50','70','80'])a.store.upsertWork({aweme_id:id,item_title:'order '+id,author:{nickname:'fixture'},video:{cover:{url_list:[`https://p3.douyinpic.com/${id}.png`]},play_addr:{url_list:[]}}});
 a.store.ingestMembers('9',['80','20','50'],true);a.store.ingestMembers('6',['70','10','40'],true);a.fetchCover=async url=>{await new Promise(r=>setTimeout(r,url.includes('10.png')?40:1));return new Response(previewPNG,{headers:{'content-type':'image/png'}});};await a.sync();const b=await f.client('PC-B');let original=a.store.snapshot(),restored=b.store.snapshot();assert.deepEqual(restored.members,original.members);assert.deepEqual(restored.pendingMembers,original.pendingMembers);assert.deepEqual(restored.members.__all__,['80','20','50','70','10','40']);assert.equal(restored.pendingMembers.__all__.length,6);
 a.store.ingestMembers('__all__',['40','80','10','20','70','50'],true);await a.sync();await b.check();restored=b.store.snapshot();assert.deepEqual(restored.members.__all__,['40','80','10','20','70','50']);assert.deepEqual(restored.members['9'],['80','20','50']);assert.deepEqual(restored.members['6'],['70','10','40']);assert.equal(restored.pendingMembers.__all__.length,0);assert.ok(restored.works.every(w=>w.backupCover&&!w.local&&!w.backedUp));
});
test('stopped partial read publishes the same visible order that a clean PC restores',async t=>{
 const f=await fixture(t),a=await f.client('PC-A');const raw=id=>({aweme_id:id,item_title:'order '+id,author:{nickname:'fixture'},video:{cover:{url_list:[`https://p3.douyinpic.com/${id}.png`]},play_addr:{url_list:[]}}});for(const id of ['3','8'])a.store.upsertWork(raw(id));a.store.ingestMembers('__all__',['3','8'],true);
 const run=a.store.sync.start('__all__',{readAll:false});a.store.sync.applyPage(run,['90','10','70'].map(raw),{next:'30',complete:false},{maxNew:2});a.store.sync.finish(run,false,'stopped');a.store.save();const original=a.store.snapshot();assert.deepEqual(original.members.__all__,['90','10','3','8']);a.fetchCover=async()=>new Response(previewPNG,{headers:{'content-type':'image/png'}});await a.sync();const b=await f.client('PC-CLEAN');const restored=b.store.snapshot();assert.deepEqual(restored.members,original.members);assert.deepEqual(restored.pendingMembers,original.pendingMembers);assert.equal(restored.collections.find(c=>c.id==='__all__').complete,false);assert.equal(restored.works.some(w=>w.id==='70'),false);assert.equal(b.store.all('downloads').length,0);
});
test('fresh PC preserves folder order for pending total members across NAS replay and later total confirmation',async t=>{
 const f=await fixture(t),a=await f.client('PC-A');for(const id of ['30','10','20','40'])a.store.upsertWork({aweme_id:id,author:{nickname:'fixture'},video:{play_addr:{url_list:[]}}});a.store.discoverCollections([{collects_id:'9',collects_name:'fixture'}]);a.store.setAdded(['9']);a.store.ingestMembers('9',['30','10','20'],true);a.store.ingestMembers('__all__',['40'],false);await a.sync();
 const b=await f.client('PC-B');assert.equal(b.store.all('downloads').length,0);assert.deepEqual(b.store.snapshot().members['9'],['30','10','20']);assert.deepEqual(b.store.snapshot().members.__all__,['40','30','10','20']);assert.deepEqual(b.store.snapshot().pendingMembers.__all__,['30','10','20']);assert.deepEqual(b.store.snapshot().members,a.store.snapshot().members);
 a.store.ingestMembers('__all__',['20','40','30','10'],true);await a.sync();await b.check();assert.deepEqual(b.store.snapshot().members.__all__,['20','40','30','10']);assert.deepEqual(b.store.snapshot().members['9'],['30','10','20']);assert.deepEqual(b.store.snapshot().pendingMembers.__all__,[]);
});
test('two PCs share records, keep media local, transfer ownership and commit only tag changes',async t=>{
 const f=await fixture(t),a=await f.client('PC-A',true);assert.equal(a.status.writable,true);await a.sync();assert.equal(a.status.phase,'synced');assert.equal(a.status.lastSync.name,'PC-A');assert.equal(fs.readFileSync(path.join(a.store.download('123').path,'video.mp4'),'utf8'),'media-fixture');
 const b=await f.client('PC-B');assert.equal(b.status.writable,false);assert.ok(b.store.work('123'));assert.equal(b.store.download('123'),null);assert.ok(b.store.get('backup_downloads','123'));assert.throws(()=>b.store.put('local_tags','123',{id:'123',tags:['blocked']}));
 await a.release();await b.check();assert.equal(b.status.writable,true);b.store.put('local_tags','123',{id:'123',tags:['new']});b.store.save();await b.sync();assert.equal(b.status.lastSync.count,1);assert.equal(b.status.lastSync.name,'PC-B');
 await b.restoreWork({id:'123'},new AbortController().signal,(w,d)=>({id:w.id,assets:d.assets}));assert.equal(fs.readFileSync(path.join(b.store.download('123').path,'video.mp4'),'utf8'),'media-fixture');
 const originalDownload=b.transport.download;b.transport.download=async()=>{throw new Error('Unexpected duplicate NAS transfer');};const queue=new DownloadQueue(b.store,{resolveWork:async()=>{throw new Error('Unexpected Douyin lookup');}},async()=>{throw new Error('Unexpected Douyin download');},()=>{});queue.backupRestore=(job,signal)=>b.restoreWork(job,signal,()=>({}));await queue.saveWork({id:'123'},new AbortController().signal);b.transport.download=originalDownload;
 await b.release();await a.check();assert.deepEqual(a.store.get('local_tags','123').tags,['new']);assert.ok(a.store.download('123'));assert.equal(a.status.pending,false);
});
test('read-only second PC fetches verified NAS covers without downloading a work and reuses them offline',async t=>{
 const f=await fixture(t),a=await f.client('PC-A',true),record=a.store.download('123');
 const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==','base64');
 fs.writeFileSync(path.join(record.path,'cover.png'),bytes);record.assets.push({key:'image-0',file:'cover.png',kind:'image',size:bytes.length});a.store.put('downloads','123',record);a.store.save();await a.sync();
 const b=await f.client('PC-B');assert.equal(b.status.writable,false);let requests=0;const download=b.transport.download.bind(b.transport);b.transport.download=(...args)=>{requests++;return download(...args);};
 const [first,second]=await Promise.all([b.covers.get('123'),b.covers.get('123')]);assert.equal(first,second);assert.equal(requests,1);assert.ok(fs.readFileSync(first).equals(bytes));assert.equal(b.store.download('123'),null);assert.equal(b.status.pending,false);assert.equal(fs.existsSync(path.join(b.profile,'login-state.bin')),false);
 await f.service.close();b.unavailable('offline');assert.equal(await b.covers.get('123'),first);assert.equal(requests,1);
});
test('NAS cover cache rejects corrupt objects instead of displaying them',async t=>{
 const f=await fixture(t),a=await f.client('PC-A',true),record=a.store.download('123');const bytes=Buffer.from('cover-fixture');fs.writeFileSync(path.join(record.path,'cover.jpg'),bytes);record.assets.push({key:'cover',file:'cover.jpg',kind:'image',size:bytes.length});a.store.put('downloads','123',record);a.store.save();await a.sync();
 const b=await f.client('PC-B');fs.writeFileSync(path.join(f.dir,'server','objects',sha256(bytes)),Buffer.alloc(bytes.length));await assert.rejects(b.covers.get('123'),/校验失败/);assert.equal(b.covers.pending.size,0);assert.equal(b.store.download('123'),null);
});
test('disconnect preserves local changes and forbids additional edits',async t=>{const f=await fixture(t),a=await f.client('PC-A',true);await a.sync();a.store.put('local_tags','123',{id:'123',tags:['pending']});a.store.save();await f.service.close();await a.poll();assert.equal(a.status.writable,false);assert.equal(a.status.pending,true);assert.deepEqual(a.store.get('local_tags','123').tags,['pending']);assert.throws(()=>a.store.put('local_tags','123',{id:'123',tags:['no']}));});
test('different unsynced changes on both PCs are preserved as a conflict',async t=>{const f=await fixture(t),a=await f.client('PC-A',true);await a.sync();const b=await f.client('PC-B');a.store.put('local_tags','123',{id:'123',tags:['A pending']});a.store.save();await a.release();await b.check();b.store.put('local_tags','123',{id:'123',tags:['B committed']});b.store.save();await b.sync();await b.release();await a.check();assert.equal(a.status.phase,'conflict');assert.equal(a.status.writable,false);assert.deepEqual(a.store.get('local_tags','123').tags,['A pending']);});
test('resumable uploads must verify before commit; wrong hashes and stale commits are rejected',async t=>{const f=await fixture(t),a=await f.client('PC-A'),bytes=Buffer.from('resumable fixture'),sha=sha256(bytes),transport=a.transport;const first=bytes.subarray(0,5);await transport.json('PUT','/v1/uploads/'+sha,{bytes:first,headers:{'upload-length':String(bytes.length),'upload-offset':'0'}});assert.equal((await transport.json('GET','/v1/uploads/'+sha)).offset,5);
 const entry={table:'downloads',key:'1',body:{id:'1',assets:[{key:'video',file:'video.mp4',kind:'video',size:bytes.length,sha256:sha}]}};
 await assert.rejects(transport.json('POST','/v1/commit',{data:{libraryId:a.meta.libraryId,baseRevision:0,changes:[entry]}}),e=>e.status===409);
 await transport.json('PUT','/v1/uploads/'+sha,{bytes:bytes.subarray(5),headers:{'upload-length':String(bytes.length),'upload-offset':'5'}});assert.equal((await transport.json('GET','/v1/uploads/'+sha)).complete,true);
 await transport.json('POST','/v1/commit',{data:{libraryId:a.meta.libraryId,baseRevision:0,changes:[entry]}});await assert.rejects(transport.json('POST','/v1/commit',{data:{libraryId:a.meta.libraryId,baseRevision:0,changes:[]}}),e=>e.status===409);
 await assert.rejects(transport.json('PUT','/v1/uploads/'+'0'.repeat(64),{bytes:Buffer.from('bad'),headers:{'upload-length':'3','upload-offset':'0'}}),e=>e.status===422);
 const denied=new BackupTransport({url:f.url,token:'wrong',deviceId:randomUUID()});await assert.rejects(denied.json('GET','/v1/status'),e=>e.status===401);
});
test('a lost commit acknowledgement is recovered without duplicate commits or a false conflict',async t=>{const f=await fixture(t),a=await f.client('PC-A',true),original=a.transport.json.bind(a.transport);let drop=true;a.transport.json=async(method,route,options)=>{const result=await original(method,route,options);if(drop&&route==='/v1/commit'){drop=false;throw new Error('simulated lost response');}return result;};await assert.rejects(a.sync(),/lost response/);assert.ok(a.meta.pendingCommit);assert.equal(f.service.status().revision,1);await a.check();assert.equal(a.status.writable,true);assert.equal(a.status.phase,'synced');assert.equal(a.meta.pendingCommit,undefined);assert.equal(f.service.status().revision,1);});
test('local edits continue during media upload and remain pending for the next commit',async t=>{const f=await fixture(t),a=await f.client('PC-A',true),upload=a.transport.upload.bind(a.transport);let started,release;const begun=new Promise(r=>started=r),hold=new Promise(r=>release=r);a.transport.upload=async(...args)=>{started();await hold;return upload(...args);};const syncing=a.sync();await begun;a.store.put('local_tags','123',{id:'123',tags:['edited during upload']});a.store.save();assert.equal(a.status.writable,true);release();await syncing;assert.equal(a.status.pending,true);await a.sync();assert.equal(a.status.pending,false);assert.equal(a.status.lastSync.count,1);});
test('a complete upload interrupted before verification can finish without retransmitting bytes',async t=>{const f=await fixture(t),a=await f.client('PC-A'),bytes=Buffer.from('complete but not finalized'),sha=sha256(bytes),source=path.join(f.dir,'source.bin');fs.writeFileSync(source,bytes);fs.writeFileSync(path.join(f.dir,'server','uploads',sha+'.part'),bytes);await a.transport.upload(source,{sha256:sha,size:bytes.length});assert.equal((await a.transport.json('GET','/v1/uploads/'+sha)).complete,true);});
test('TLS certificate pinning rejects the wrong server before sending the API token',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-tls-')),key=path.join(dir,'key.pem'),cert=path.join(dir,'cert.pem'),openssl=process.env.OPENSSL||(process.platform==='win32'?'C:\\Program Files\\Git\\usr\\bin\\openssl.exe':'openssl');execFileSync(openssl,['req','-x509','-newkey','rsa:2048','-nodes','-keyout',key,'-out',cert,'-days','1','-subj','/CN=localhost'],{stdio:'ignore'});const token=randomBytes(32).toString('hex'),service=createBackupServer({dataDir:path.join(dir,'server'),token,tls:{key:fs.readFileSync(key),cert:fs.readFileSync(cert)}});const address=await service.listen();let requests=0;service.server.on('request',()=>requests++);const bad=new BackupTransport({url:'https://127.0.0.1:'+address.port,token,fingerprint:'0'.repeat(64),deviceId:randomUUID()});const good=new BackupTransport({url:'https://127.0.0.1:'+address.port,token,fingerprint:new X509Certificate(fs.readFileSync(cert)).fingerprint256,deviceId:randomUUID()});try{await assert.rejects(bad.json('GET','/v1/status'),/证书/);assert.equal(requests,0);assert.ok((await good.json('GET','/v1/status')).libraryId);}finally{bad.close();good.close();await service.close();assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true});}});
