import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Store} from '../electron/store.mjs';
import {Collector} from '../electron/account-collector.mjs';
import {TOTAL} from '../electron/model.mjs';
const raw=id=>({aweme_id:String(id),desc:'作品 '+id,author:{uid:'7',nickname:'作者'}});
const ids=(n,start=1)=>Array.from({length:n},(_,i)=>String(i+start));
const page=(list,next='1',complete=false)=>({items:list.map(raw),next,complete});
async function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cx-incremental-'));let store=await Store.open(path.join(dir,'library.sqlite'),path.join(dir,'media'));store.setSetting('browserAccountKey','uid:1');t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});return {get store(){return store;},async reopen(){store.close();store=await Store.open(path.join(dir,'library.sqlite'),path.join(dir,'media'));return store;},dir};}
function seed(store,list,scope=TOTAL,{legacy=true}={}){store.db.run('BEGIN');try{for(const id of list)store.upsertWork(raw(id));store.ingestMembers(scope,list,true);if(legacy){store.sync.write({collectionId:scope,status:'complete',accountKey:'uid:1',count:list.length,nextCursor:null,pages:1});store.collectionReads.importLegacy(scope);}store.db.run('COMMIT');}catch(e){store.db.run('ROLLBACK');throw e;}}
function order(store,scope=TOTAL){return store.collectionReads.membership(scope).map(r=>r.work_id);}
function fakeCollector(store,responses){const c=new Collector(store,()=>{},{profile:{},vault:{load:()=>null},browser:{},delay:async()=>{}});c.isAuthenticated=async()=>true;const calls=[];c.request=async(_path,opts)=>{calls.push(opts);const value=await responses(calls.length,opts);return value;};return {c,calls};}
test('20,000-item legacy baseline stops after ordered overlap and retains history',async t=>{const {store}=await setup(t);const old=ids(20000);seed(store,old);const reads=store.collectionReads,run=reads.start(TOTAL,'quick');assert.equal(run.baselineKnown,true);reads.apply(run,page(['30001',...old.slice(0,29)],'30'));reads.apply(run,page(old.slice(29,59),'60'));assert.equal(run.status,'running');reads.apply(run,page(old.slice(59,89),'90'));assert.equal(run.outcome,'matched');assert.equal(run.added,1);assert.deepEqual(order(store),['30001',...old]);assert.deepEqual(reads.baseline(TOTAL).fullIds,old);assert.equal(reads.baseline(TOTAL).anchorIds[0],'30001');});
test('no new collection ends on two-page overlap without reading all works',async t=>{const {store}=await setup(t);seed(store,ids(300));const {c,calls}=fakeCollector(store,async n=>({aweme_list:ids(30,(n-1)*30+1).map(raw),cursor:String(n*30),has_more:1}));await c.sync({mode:'quick'});assert.equal(calls.length,2);assert.equal(store.collectionReads.get(TOTAL,'quick').outcome,'matched');assert.equal(c.status.readProgress.added,0);});
test('missing baseline needs confirmation before any request; confirmed check passes 500 and preserves suspicious history',async t=>{const {store}=await setup(t);seed(store,ids(20000),TOTAL,{legacy:false});const {c,calls}=fakeCollector(store,async(_n,opts)=>{const start=Number(opts.form.cursor);return {aweme_list:ids(30,start+1).map(raw),cursor:String(start+30),has_more:start<600?1:0};});await assert.rejects(c.sync({mode:'quick'}),/确认/);assert.equal(calls.length,0);assert.equal(store.collectionReads.get(TOTAL,'quick'),null);await c.sync({mode:'quick',allowFullScan:true});assert.equal(calls.length,21);assert.equal(store.collectionReads.get(TOTAL,'quick').count,630);assert.equal(store.collectionReads.get(TOTAL,'quick').outcome,'review');assert.equal(order(store).length,20000);});
test('short pages continue beyond twenty until the explicit last page',async t=>{const {store}=await setup(t);const {c,calls}=fakeCollector(store,async n=>({aweme_list:[raw(n)],cursor:String(n),has_more:n<23?1:0}));await c.sync({mode:'quick',allowFullScan:true});assert.equal(calls.length,23);assert.equal(store.collectionReads.get(TOTAL,'quick').outcome,'end');});
test('800 new collections are all checked before the 60-work historical overlap',async t=>{const {store}=await setup(t);const old=ids(20000),fresh=ids(800,90001);seed(store,old);const stream=[...fresh,...old];const {c,calls}=fakeCollector(store,async(_n,opts)=>{const start=Number(opts.form.cursor);return {aweme_list:stream.slice(start,start+30).map(raw),cursor:String(start+30),has_more:1};});await c.sync({mode:'quick'});const run=store.collectionReads.get(TOTAL,'quick');assert.equal(calls.length,29);assert.equal(run.count,870);assert.equal(run.added,800);assert.equal(run.outcome,'matched');assert.deepEqual(order(store),stream);});
test('old limited checkpoint resumes its cursor and keeps accumulated discoveries',async t=>{const {store}=await setup(t);const old=ids(2000),fresh=ids(800,90001),stream=[...fresh,...old];seed(store,old);const r=store.collectionReads,previous=r.start(TOTAL,'quick');for(let i=0;i<510;i+=30)r.apply(previous,page(fresh.slice(i,i+30),String(i+30)));r.finish(previous,'limit');assert.match(r.info(TOTAL).quick.reason,/旧版/);const {c,calls}=fakeCollector(store,async(_n,opts)=>{const start=Number(opts.form.cursor);return {aweme_list:stream.slice(start,start+30).map(raw),cursor:String(start+30),has_more:1};});await c.sync({mode:'quick',resume:true});assert.equal(calls[0].form.cursor,'510');assert.equal(r.get(TOTAL,'quick').added,800);assert.equal(r.get(TOTAL,'quick').outcome,'matched');assert.deepEqual(order(store),stream);});
test('globally known author work counts as a new collection; hidden members count restored',async t=>{const {store}=await setup(t);seed(store,ids(100));store.upsertWork(raw('999'));store.deleteReadRecords(['1','90']);store.put('downloads','999',{id:'999',collectionId:'author:7',directory:'saved',status:'complete'});const run=store.collectionReads.start(TOTAL,'quick');store.collectionReads.apply(run,page(['999',...ids(30)],'31'));store.collectionReads.finish(run,'paused');assert.equal(run.added,1);assert.equal(run.restored,1);assert.equal(store.work('1').readHidden,false);assert.equal(store.work('90').readHidden,true);assert.equal(store.download('999').directory,'saved');});
test('scope membership, re-favoriting and changed metadata retain uniqueness and returned order',async t=>{const {store}=await setup(t);seed(store,ids(100));store.discoverCollections([{collects_id:'77',collects_name:'夹'}]);store.setAdded(['77']);seed(store,ids(80), '77');const run=store.collectionReads.start('77','quick');store.collectionReads.apply(run,page(['90','80','1','2'],'4'));store.collectionReads.finish(run,'paused');assert.equal(run.added,1);assert.deepEqual(order(store,'77').slice(0,5),['90','80','1','2','3']);assert.equal(new Set(order(store,'77')).size,81);});
test('unordered known works and duplicate pages cannot trigger early completion',async t=>{const {store}=await setup(t);seed(store,ids(200));const r=store.collectionReads,run=r.start(TOTAL,'quick');r.apply(run,page(ids(30).reverse(),'30'));r.apply(run,page(ids(30,31).reverse(),'60'));assert.equal(run.status,'running');r.apply(run,page(ids(30,31),'90'));assert.equal(run.streak,0);assert.equal(run.count,60);});
test('suspicious empty result preserves members and baseline until explicit confirmation',async t=>{const {store,dir}=await setup(t);seed(store,ids(100));const file=path.join(dir,'media','keep.txt');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,'unchanged');const r=store.collectionReads,run=r.start(TOTAL,'full');r.apply(run,page([],null,true));assert.equal(run.outcome,'review');assert.equal(order(store).length,100);assert.equal(r.baseline(TOTAL).fullIds.length,100);assert.throws(()=>r.confirm(TOTAL,'full','wrong'),/变化/);r.confirm(TOTAL,'full',run.token);assert.equal(order(store).length,0);assert.equal(fs.readFileSync(file,'utf8'),'unchanged');assert.equal(r.baseline(TOTAL).fullIds.length,0);});
test('full read reconciles modest removals; quick overlap retains unvisited cancellations',async t=>{const {store}=await setup(t);seed(store,ids(100));const r=store.collectionReads;let run=r.start(TOTAL,'quick');r.apply(run,page(ids(30),'30'));r.apply(run,page(ids(30,31),'60'));assert.equal(order(store).length,100);run=r.start(TOTAL,'full');r.apply(run,page(ids(80),null,true));assert.equal(run.outcome,'end');assert.deepEqual(order(store),ids(80));});
test('bad cursor, malformed work or empty nonterminal page rolls back works and cursor',async t=>{const {store}=await setup(t);const r=store.collectionReads,run=r.start(TOTAL,'quick');for(const result of [page(['1'],'0'),{items:[raw('1'),raw('invalid')],next:'30'},page([],'30')]){assert.throws(()=>r.apply(run,result));assert.equal(run.count,0);assert.equal(run.nextCursor,'0');assert.equal(store.work('1'),null);assert.equal(r.seen(run,'0'),false);}r.apply(run,page(['1'],'30'));assert.equal(run.count,1);});
test('late response after stop never writes a page',async t=>{const {store}=await setup(t);const {c}=fakeCollector(store,async()=>{c.stop();return {aweme_list:[raw('1')],cursor:'30',has_more:1};});await c.sync({mode:'quick',allowFullScan:true});assert.equal(store.work('1'),null);assert.equal(store.collectionReads.get(TOTAL,'quick').nextCursor,'0');assert.equal(c.busy,false);});
test('request failures persist previous page and resumable cursor',async t=>{const {store}=await setup(t);const {c}=fakeCollector(store,async n=>{if(n===2)throw Error('HTTP 403');return {aweme_list:[raw('1')],cursor:'30',has_more:1};});await c.sync({mode:'quick',allowFullScan:true});assert.equal(store.collectionReads.get(TOTAL,'quick').nextCursor,'30');assert.equal(store.collectionReads.info(TOTAL).quick.canResume,true);assert.deepEqual(order(store),['1']);assert.match(c.status.message,/403/);});
test('process recovery preserves page and independent full/quick progress',async t=>{const f=await setup(t);seed(f.store,ids(100));let r=f.store.collectionReads,full=r.start(TOTAL,'full');r.apply(full,page(ids(20),'20'));r.finish(full,'paused');let quick=r.start(TOTAL,'quick');r.apply(quick,page(['999',...ids(20)],'21'));await f.reopen();r=f.store.collectionReads;assert.equal(r.info(TOTAL).quick.canResume,true);assert.equal(r.info(TOTAL).full.canResume,true);assert.equal(r.get(TOTAL,'full').nextCursor,'20');assert.equal(order(f.store)[0],'999');});
test('older resumed full read never overwrites newer quick order or baseline',async t=>{const {store}=await setup(t);seed(store,ids(100));const r=store.collectionReads;let full=r.start(TOTAL,'full');r.apply(full,page(ids(30),'30'));r.finish(full,'paused');const quick=r.start(TOTAL,'quick');r.apply(quick,page(['999',...ids(29)],'30'));r.apply(quick,page(ids(30,30),'60'));r.apply(quick,page(ids(30,60),'90'));assert.equal(quick.outcome,'matched');full=r.start(TOTAL,'full',{resume:true});r.apply(full,page(ids(70,31),null,true));assert.equal(full.outcome,'end-stale');assert.equal(order(store)[0],'999');assert.equal(r.baseline(TOTAL).anchorIds[0],'999');});
test('older full checkpoint cannot move a work back from a newer folder',async t=>{const {store}=await setup(t);store.discoverCollections([{collects_id:'77',collects_name:'一'},{collects_id:'88',collects_name:'二'}]);store.setAdded(['77','88']);seed(store,ids(100),'77');const r=store.collectionReads;let full=r.start('77','full');r.apply(full,page(ids(30),'30'));r.finish(full,'paused');store.ingestMembers('88',['1'],false);full=r.start('77','full',{resume:true});r.apply(full,page(ids(70,31),null,true));assert.equal(order(store,'77').includes('1'),false);assert.deepEqual(order(store,'88'),['1']);});
test('changed account rejects resume and stale review confirmation',async t=>{const {store}=await setup(t);seed(store,ids(100));const r=store.collectionReads;const run=r.start(TOTAL,'full');r.apply(run,page([],null,true));store.setSetting('browserAccountKey','uid:2');assert.equal(r.info(TOTAL).full.canConfirm,false);assert.throws(()=>r.confirm(TOTAL,'full',run.token));assert.equal(r.baseline(TOTAL),null);});
test('legacy partial checkpoint can be resumed without destroying legacy rows',async t=>{const {store}=await setup(t);const old=store.sync.start(TOTAL,{readAll:true});store.sync.applyPage(old,[raw('1')],{next:'30',complete:false});store.sync.finish(old,false);const run=store.collectionReads.start(TOTAL,'full',{resume:true});assert.equal(run.count,1);assert.equal(run.nextCursor,'30');store.collectionReads.apply(run,page(['2'],null,true));assert.deepEqual(order(store),['1','2']);assert.equal(store.sync.get(TOTAL).status,'paused');});

test('publication failure keeps a running checkpoint and does not claim completion',async t=>{const {store}=await setup(t);seed(store,ids(100));const r=store.collectionReads,run=r.start(TOTAL,'quick');r.apply(run,page(['999'],'30'));const put=store.put.bind(store);store.put=(table,...args)=>{if(table==='collection_read_runs')throw Error('synthetic disk failure');return put(table,...args);};assert.throws(()=>r.finish(run,'limit'),/disk failure/);store.put=put;assert.equal(run.status,'running');assert.equal(run.outcome,null);assert.equal(order(store)[0],'1');assert.equal(r.get(TOTAL,'quick').nextCursor,'30');r.finish(run,'paused');assert.equal(order(store)[0],'999');});

test('stopped operation reports saved progress instead of an AbortError',async t=>{const {store}=await setup(t);const {c}=fakeCollector(store,async()=>{c.stop();throw new DOMException('This operation was aborted','AbortError');});await c.sync({mode:'quick',allowFullScan:true});assert.match(c.status.message,/已停止/);assert.doesNotMatch(c.status.message,/aborted/);});
