import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {apiRequest} from '../electron/browser-api.mjs';import {Collector} from '../electron/account-collector.mjs';import {Store} from '../electron/store.mjs';import {CreatorDetails} from '../electron/creator-details.mjs';import {CREATOR_INFO_VERSION} from '../shared/creators.mjs';
const raw=JSON.parse(fs.readFileSync(new URL('./fixtures/coauthor-work.json',import.meta.url)));
const capabilities={update_version_code:'170400',pc_client_type:'1',version_code:'190500',version_name:'19.5.0'};
test('normal browser API requests advertise creator fields for detail, collection and author list routes',()=>{
 for(const [route,method]of [['/aweme/v1/web/aweme/detail/','GET'],['/aweme/v1/web/aweme/listcollection/','POST'],['/aweme/v1/web/collects/video/list/','GET'],['/aweme/v1/web/aweme/post/','GET']]){const request=apiRequest(route,{method,params:{aweme_id:raw.aweme_id},...(method==='POST'?{form:{cursor:'0'}}:{})}),url=new URL(request.url);for(const [key,value]of Object.entries(capabilities))assert.equal(url.searchParams.get(key),value);assert.equal(url.searchParams.get('aweme_id'),raw.aweme_id);if(method==='POST')assert.equal(request.body,'cursor=0');}
});
test('real collector request shape recovers a fresh 0.3.17 false-empty cache and queries only the missing creator profile',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'cx-creator-request-')),store=await Store.open(path.join(root,'db.sqlite'),path.join(root,'media'));store.upsertWork(raw);store.put('works',raw.aweme_id,{...store.work(raw.aweme_id),coAuthors:[],creatorInfoVersion:undefined,coAuthorsState:undefined,creatorsCheckedAt:new Date().toISOString()});const calls=[];
 const profile={getUserAgent:()=> 'Fixture/1',fetch:async value=>{const url=new URL(value);calls.push(url);if(url.pathname.includes('/aweme/detail/')){const w=structuredClone(raw);if(!Object.entries(capabilities).every(([k,v])=>url.searchParams.get(k)===v))delete w.cooperation_info;return new Response(JSON.stringify({status_code:0,aweme_detail:w}));}assert.match(url.pathname,/user\/profile\/other/);return new Response(JSON.stringify({status_code:0,user:{...raw.cooperation_info.co_creators[0],unique_id:'37386365831'}}));}};
 const c=new Collector(store,()=>{},{profile,vault:{load:()=>null},browser:{},delay:async()=>{}});await c.ready;c.status.connected=true;c.isAuthenticated=async()=>true;t.after(()=>{c.closed=true;clearTimeout(c.browserIdle);store.close();assert.equal(path.dirname(root),os.tmpdir());fs.rmSync(root,{recursive:true,force:true});});
 await new CreatorDetails(c).refresh(raw.aweme_id);const updated=store.work(raw.aweme_id);assert.equal(updated.creatorInfoVersion,CREATOR_INFO_VERSION);assert.equal(updated.coAuthorsState,'verified');assert.equal(updated.coAuthors[0].nickname,'偷懒噜');assert.equal(updated.coAuthors[0].uniqueId,'37386365831');assert.equal(calls.length,2);assert.equal(calls[1].searchParams.get('sec_user_id'),raw.cooperation_info.co_creators[0].sec_uid);
 store.put('works',raw.aweme_id,{...updated,coAuthors:[],coAuthorsState:'unknown'});await new CreatorDetails(c).refresh(raw.aweme_id);assert.equal(store.work(raw.aweme_id).coAuthors[0].nickname,'偷懒噜');assert.equal(calls.length,3,'unknown responses must be retried even with a recent timestamp');
});
