import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';
import {FlatDownloadQueue} from '../electron/flat-downloads.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
const image=(id,count=2)=>({id,name:'作品 '+id,type:'images',author:{nickname:'作者'},images:Array.from({length:count},(_,index)=>({index,urls:[`https://p3.douyinpic.com/${id}/${index}`]}))});
const video=id=>({id,name:'视频 '+id,type:'video',author:{nickname:'作者'},videoUrls:[`https://v3.douyinvod.com/${id}`],coverUrls:[`https://p3.douyinpic.com/${id}/cover`]});
const bytes=Buffer.from('complete-fixture-media');
function fixture(t,works=[image('1'),video('2')]){
 const base=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-flat-')),directory=path.join(base,'outputs'),root=path.join(base,'library'),profile=path.join(base,'profile');for(const p of [directory,root,profile])fs.mkdirSync(p);
 let calls=0,resolveCalls=0;const records={};const store={root,work:id=>works.find(w=>w.id===id),download:id=>records[id],put:()=>assert.fail('no library write'),save:()=>assert.fail('no save'),setSetting:()=>assert.fail('no settings write')};
 const q=new FlatDownloadQueue({store,protectedPaths:[profile],collector:{resolveMediaOnly:async id=>{resolveCalls++;return works.find(w=>w.id===id);}},fetchMedia:async url=>{calls++;return new Response(bytes,{headers:{'content-type':url.includes('douyinpic')?'image/jpeg':'video/mp4','content-length':String(bytes.length),etag:'"fixture"'}});}});
 t.after(async()=>{await q.dispose();assert.equal(path.dirname(base),os.tmpdir());assert.ok(path.basename(base).startsWith('cangxia-flat-'));fs.rmSync(base,{recursive:true,force:true});});
 return {q,base,directory,root,profile,records,calls:()=>calls,resolves:()=>resolveCalls,start:async(ids=['1','2'],cover=false,allow=false)=>{const intent=q.prepare(directory,ids,cover);const result=q.start(intent.token,allow);await q.waitForIdle();return result;}};
}
test('one-off media is flat, ordered, cover opt-in, and never changes library/history',async t=>{
 const f=fixture(t);await f.start(['2','1']);assert.deepEqual(fs.readdirSync(f.directory).sort(),['0001_作者_2.mp4','0002_作者_1_01.jpg','0002_作者_1_02.jpg']);assert.equal(f.q.state().batches[0].complete,2);assert.equal(f.q.state().batches[0].files,3);assert.equal(f.calls(),3);assert.equal(fs.readdirSync(f.root).length,0);
 const other=path.join(f.base,'covers');fs.mkdirSync(other);const intent=f.q.prepare(other,['2'],true);f.q.start(intent.token);await f.q.waitForIdle();assert.deepEqual(fs.readdirSync(other).sort(),['0001_作者_2.mp4','0001_作者_2_封面.jpg']);
});
test('nonempty directory needs confirmation even when it changed after preparation; existing bytes never overwritten',async t=>{
 const f=fixture(t,[video('2')]),intent=f.q.prepare(f.directory,['2']);assert.equal(intent.nonempty,false);const old=path.join(f.directory,'0001_作者_2.mp4');fs.writeFileSync(old,'different');assert.deepEqual(f.q.start(intent.token),{needsConfirmation:true});f.q.start(intent.token,true);await f.q.waitForIdle();assert.equal(fs.readFileSync(old,'utf8'),'different');assert.deepEqual(fs.readFileSync(path.join(f.directory,'0001_作者_2_2.mp4')),bytes);
 await f.start(['2'],false,true);assert.equal(f.q.state().batches[1].skipped,1);assert.equal(fs.readdirSync(f.directory).length,2);
});
test('verified local files copy without login/network or consuming originals; corrupt same-size file uses network',async t=>{
 const f=fixture(t,[video('2')]),source=path.join(f.root,'source');fs.mkdirSync(source);fs.writeFileSync(path.join(source,'v.mp4'),bytes);f.records['2']={path:source,assets:[{key:'video',file:'v.mp4',size:bytes.length,sha256:hash(bytes)}]};await f.start(['2']);assert.equal(f.calls(),0);assert.equal(f.resolves(),0);assert.deepEqual(fs.readFileSync(path.join(source,'v.mp4')),bytes);
 fs.writeFileSync(path.join(source,'v.mp4'),Buffer.alloc(bytes.length,1));await f.start(['2'],false,true);assert.equal(f.calls(),1);assert.equal(f.q.state().batches[1].skipped,1);
});
test('partial failures stay failed; retry skips already-complete files and completes only after all media',async t=>{
 const f=fixture(t,[image('1')]);let fail=true,firstCalls=0;f.q.fetchMedia=async url=>{if(url.endsWith('/0'))firstCalls++;if(url.endsWith('/1')&&fail)return new Response('bad',{status:500});return new Response(bytes,{headers:{'content-type':'image/jpeg'}});};const {id}=await f.start(['1']);assert.equal(f.q.state().batches[0].failed,1);assert.equal(f.q.state().batches[0].files,1);assert.equal(f.q.state().batches[0].complete,0);fail=false;f.q.retry(id);await f.q.waitForIdle();assert.equal(f.q.state().batches[0].complete,1);assert.equal(firstCalls,1);assert.equal(fs.readdirSync(f.directory).length,2);
});
test('pause resumes only in memory using verified Range, with no checkpoint JSON; cancel keeps full media and removes temporary bytes',async t=>{
 const f=fixture(t,[image('1')]);let paused=false,range;f.q.fetchMedia=async(url,options)=>{if(url.endsWith('/0'))return new Response(bytes,{headers:{'content-type':'image/jpeg'}});range=options.headers.Range;if(!paused)return new Response(new ReadableStream({start(c){c.enqueue(bytes.subarray(0,5));options.signal.addEventListener('abort',()=>c.error(Error('pause')),{once:true});}}),{headers:{'content-type':'image/jpeg','content-length':String(bytes.length),etag:'"fixture"'}});return new Response(bytes.subarray(5),{status:206,headers:{'content-type':'image/jpeg','content-length':String(bytes.length-5),'content-range':`bytes 5-${bytes.length-1}/${bytes.length}`,etag:'"fixture"'}});};
 const intent=f.q.prepare(f.directory,['1']);const {id}=f.q.start(intent.token);while(!f.q.checkpoints.size&&!fs.readdirSync(f.q.get(id).stage).some(n=>n.endsWith('.part')))await new Promise(r=>setTimeout(r,5));await new Promise(r=>setTimeout(r,30));f.q.pause(id);await f.q.waitForIdle();paused=true;assert.ok(f.q.checkpoints.size);assert.ok(fs.readdirSync(f.q.get(id).stage).every(n=>!n.endsWith('.json')));assert.equal(f.q.state().batches[0].files,1);f.q.resume(id);await f.q.waitForIdle();assert.equal(range,'bytes=5-');assert.equal(f.q.state().batches[0].complete,1);assert.deepEqual(fs.readFileSync(path.join(f.directory,'0001_作者_1_02.jpg')),bytes);
 const intent2=f.q.prepare(f.directory,['1']);const b=f.q.start(intent2.token,true);f.q.pause(b.id);await f.q.waitForIdle();fs.writeFileSync(path.join(f.q.get(b.id).stage,'owned.part'),'partial');await f.q.cancel(b.id);assert.equal(fs.readdirSync(f.directory).length,2);assert.equal(f.q.hasUnfinished(),false);await f.q.clear(b.id);assert.equal(f.q.state().batches.length,1);
});
test('protected directories and stale intents are refused before any output',async t=>{const f=fixture(t);assert.throws(()=>f.q.prepare(f.root,['1']),/之外/);assert.throws(()=>f.q.prepare(f.profile,['1']),/之外/);const intent=f.q.prepare(f.directory,['1']);f.q.intents.get(intent.token).expires=0;assert.throws(()=>f.q.start(intent.token),/过期/);assert.equal(fs.readdirSync(f.directory).length,0);});
test('new process has no previous tasks; shutdown removes only owned fragments and retains complete outputs',async t=>{
 const f=fixture(t,[image('1')]);const keep=path.join(f.directory,'keep.txt');fs.writeFileSync(keep,'unrelated');const intent=f.q.prepare(f.directory,['1']);const {id}=f.q.start(intent.token,true);f.q.pause(id);await f.q.waitForIdle();const stage=f.q.get(id).stage;fs.writeFileSync(path.join(stage,'owned.part'),'partial');await f.q.dispose();assert.deepEqual(fs.readdirSync(f.directory),['keep.txt']);assert.deepEqual(f.q.state().batches,[]);assert.equal(fs.readFileSync(keep,'utf8'),'unrelated');
});
test('logout pauses only batches requiring network while complete local copying can continue',async t=>{
 const f=fixture(t,[video('2')]),source=path.join(f.root,'source');fs.mkdirSync(source);fs.writeFileSync(path.join(source,'v.mp4'),bytes);f.records['2']={path:source,assets:[{key:'video',file:'v.mp4',size:bytes.length,sha256:hash(bytes)}]};let proceed;f.q.copyLocal=async()=>new Promise(r=>{proceed=r;});const {token}=f.q.prepare(f.directory,['2']);const {id}=f.q.start(token);assert.deepEqual(await f.q.networkBatchIds(),[]);f.q.get(id).jobs[0].local.assets=[];assert.deepEqual(await f.q.networkBatchIds(),[id]);proceed(null);await f.q.waitForIdle();
});
test('filesystems without hard links use exclusive verified publication and retain old colliding files',async t=>{
 const f=fixture(t,[video('2')]),original=fs.promises.link;t.after(()=>{fs.promises.link=original;});fs.promises.link=async()=>{throw Object.assign(new Error('no links'),{code:'EXDEV'});};const old=path.join(f.directory,'0001_作者_2.mp4');fs.writeFileSync(old,'keep');await f.start(['2'],false,true);assert.equal(fs.readFileSync(old,'utf8'),'keep');assert.deepEqual(fs.readFileSync(path.join(f.directory,'0001_作者_2_2.mp4')),bytes);
 const stage=path.join(f.directory,'test-stage');fs.mkdirSync(stage);const asset=path.join(stage,'source.mp4');fs.writeFileSync(asset,bytes);const b={directory:f.directory,stage,stageStat:fs.lstatSync(stage)};await assert.rejects(f.q.publish(b,{file:asset,size:bytes.length,sha256:'wrong'},'bad',new AbortController().signal),/校验失败/);assert.equal(fs.existsSync(path.join(f.directory,'bad.mp4')),false);
});
