import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {HDCover,comparableResolution,bestCover} from '../electron/hd-cover.mjs';import {DownloadQueue} from '../electron/downloads.mjs';import {Store} from '../electron/store.mjs';import {inspectWorkFiles} from '../electron/repair-check.mjs';
function png(w,h){const b=Buffer.alloc(24);Buffer.from([137,80,78,71,13,10,26,10]).copy(b);b.writeUInt32BE(w,16);b.writeUInt32BE(h,20);return b;}
async function setup(t){const base=fs.mkdtempSync(path.join(os.tmpdir(),'cx-hd-')),store=await Store.open(path.join(base,'db.sqlite'),path.join(base,'media'));store.upsertWork({aweme_id:'1',desc:'fixture',video:{width:1920,height:1080,cover:{url_list:['https://p3.douyinpic.com/cover']},play_addr:{url_list:['https://v3.douyinvod.com/video']}}});const dir=store.destination('1').dir;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'video.mp4'),'video');fs.writeFileSync(path.join(dir,'cover.png'),png(640,360));fs.writeFileSync(path.join(dir,'info.json'),'{}');const d={id:'1',path:dir,state:'complete',assets:[{key:'video',kind:'video',file:'video.mp4',size:5},{key:'cover',kind:'image',file:'cover.png',size:24,width:640,height:360},{key:'metadata',kind:'metadata',file:'info.json',size:2}]};store.put('downloads','1',d);t.after(()=>{store.close();fs.rmSync(base,{recursive:true,force:true});});return {store,d,dir};}
test('resolution follows the actual video and matching aspect, without a 720-pixel floor',()=>{assert.equal(comparableResolution({width:640,height:360},{width:640,height:360}),true);assert.equal(comparableResolution({width:720,height:540},{width:1920,height:1080}),false);assert.equal(comparableResolution({width:1440,height:1080},{width:1920,height:1080}),true);});
test('ordinary downloads never invoke HD matching, even for a small cover',async t=>{const {store}=await setup(t);store.forgetDownloads(['1']);const q=new DownloadQueue(store,{resolveWork:async()=>store.work('1')},async url=>new Response(url.includes('/video')?'video':png(320,180),{headers:{'content-type':url.includes('/video')?'video/mp4':'image/png'}}),()=>{});q.hdCovers={ensure:async()=>assert.fail('automatic matching is forbidden')};await q.saveWork({id:'1'},new AbortController().signal);assert.equal(store.download('1').state,'complete');assert.equal(store.download('1').hdCover,undefined);});
test('NAS restore completion does not start HD matching',async t=>{const {store}=await setup(t);const q=new DownloadQueue(store,{},null,()=>{});q.backupRestore=async()=>true;q.hdCovers={ensure:async()=>assert.fail('automatic matching is forbidden')};await q.saveWork({id:'1'},new AbortController().signal);});
test('legacy HD-only failure and missing optional HD file do not hide complete media',async t=>{const {store,d}=await setup(t);d.state='partial';d.hdCover={status:'failed',message:'old failure'};store.put('downloads','1',d);assert.equal(store.isDownloaded('1'),true);d.state='complete';d.assets.push({key:'cover-hd-missing',kind:'image',file:'missing.png'});store.put('downloads','1',d);assert.equal(store.isDownloaded('1'),true);assert.equal(inspectWorkFiles(store,'1').status,'complete');});
test('all distinct supplied cover renditions are checked, including later URLs',async t=>{const {store,dir}=await setup(t);const q=new DownloadQueue(store,{},async url=>new Response(png(url.endsWith('large')?1920:640,url.endsWith('large')?1080:360),{headers:{'content-type':'image/png'}}),()=>{});const a=await q.saveBestCover(dir,[{source:'cover',urls:['https://p3.douyinpic.com/small','https://p3.douyinpic.com/large']}],new AbortController().signal,()=>{});assert.equal(a.width,1920);assert.equal(a.comparisons.length,2);});
test('matching publishes a separate original-resolution asset, retains the original, and can retry without changing keys',async t=>{const {store,d,dir}=await setup(t);let matches=0;const service=new HDCover({store,extract:async req=>{if(req.mode==='probe')return {width:1920,height:1080};matches++;fs.writeFileSync(req.output,png(1440,1080));return {width:1440,height:1080,seconds:1,frame:30,correlation:.995,crop:[240,0,1440,1080]};}});const q={resolveWork:async()=>store.work('1'),saveBestCover:async()=>{throw Error('no larger platform image');}};await service.ensure(q,store.work('1'),d,new AbortController().signal,()=>{});assert.equal(d.hdCover.status,'ready');assert.equal(bestCover(d).source,'video_frame');assert.deepEqual(fs.readFileSync(path.join(dir,'cover.png')),png(640,360));assert.equal(d.assets.find(a=>a.key==='video').file,'video.mp4');const key=d.hdCover.key;await service.ensure(q,store.work('1'),d,new AbortController().signal,()=>{});assert.equal(matches,1);assert.equal(d.hdCover.key,key);assert.equal(fs.readdirSync(dir).filter(n=>n.startsWith('.cangxia')).length,0);});
test('cover-only failure stays separate from downloaded media completeness',async t=>{const {store,dir}=await setup(t);const q=new DownloadQueue(store,{},null,()=>{});q.hdCovers={ensure:async()=>{throw Error('no reliable match');}};await assert.rejects(q.saveWork({id:'1',coverOnly:true},new AbortController().signal),/no reliable match/);const saved=store.download('1');assert.equal(saved.hdCover.status,'failed');assert.equal(saved.state,'complete');assert.equal(inspectWorkFiles(store,'1').status,'complete');assert.equal(store.isDownloaded('1'),true);assert.equal(fs.readFileSync(path.join(dir,'video.mp4'),'utf8'),'video');});
test('platform cover at video resolution avoids matching and preserves existing cover',async t=>{const {store,d,dir}=await setup(t);let frames=0;const service=new HDCover({store,extract:async req=>{if(req.mode==='probe')return {width:1920,height:1080};frames++;throw Error('must not extract');}});await service.ensure({resolveWork:async()=>store.work('1'),saveBestCover:async folder=>{fs.writeFileSync(path.join(folder,'platform.png'),png(1920,1080));return {kind:'image',source:'cover',width:1920,height:1080,file:'platform.png'};}},store.work('1'),d,new AbortController().signal,()=>{});assert.equal(frames,0);assert.equal(d.hdCover.source,'cover');assert.equal(fs.readFileSync(path.join(dir,'cover.png')).length,24);});
