import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../electron/store.mjs';
const raw=id=>({aweme_id:id,desc:'work '+id,author:{nickname:'author'},images:[{url_list:['https://p3.douyinpic.com/'+id+'.png']}]});
async function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cx-organize-')),store=await Store.open(path.join(dir,'library.sqlite'),path.join(dir,'media'));t.after(()=>{store.close();assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:100});});return {store,dir};}
function local(store,id){store.upsertWork(raw(id));store.ingestMembers('__all__',[id],false);const target=store.destination(id);fs.mkdirSync(target.dir,{recursive:true});fs.writeFileSync(path.join(target.dir,'作品信息.json'),JSON.stringify({workId:id,assets:[]}));store.put('downloads',id,{id,path:target.dir,home:target.home,collectionId:target.collectionId,state:'partial',assets:[{key:'metadata',kind:'metadata',file:'作品信息.json',size:fs.statSync(path.join(target.dir,'作品信息.json')).size}]});return target.dir;}
test('targeted reconciliation never reloads the full downloads array per work and preserves untouched paths',async t=>{
 const {store}=await fixture(t);const old=local(store,'1'),untouched=local(store,'2');store.discoverCollections([{collects_id:'9',collects_name:'folder'}],true);store.setAdded(['9']);store.ingestMembers('9',['1'],true);
 const all=store.all.bind(store);store.all=table=>{assert.notEqual(table,'downloads','no full download objects during directory lookup');return all(table);};
 const progress=[];assert.deepEqual(await store.reconcilePending({onProgress:p=>progress.push(p)}),[]);assert.equal(store.download('2').path,untouched);assert.notEqual(store.download('1').path,old);assert.equal(JSON.parse(fs.readFileSync(path.join(store.download('1').path,'作品信息.json'))).collectionId,'9');assert.equal(store.localReconcile.state().pending,0);assert.ok(progress.length>=2);
});
test('stopping organizing leaves durable remaining entries and resume does not repeat completed moves',async t=>{
 const {store,dir}=await fixture(t);local(store,'1');local(store,'2');store.discoverCollections([{collects_id:'9',collects_name:'folder'}],true);store.setAdded(['9']);store.ingestMembers('9',['1','2'],true);
 await store.reconcilePending({onProgress:p=>{if(p.processed===1)store.localReconcile.stop();}});assert.equal(store.localReconcile.state().pending,1);const completed=store.download('1').path;store.close();const reopened=await Store.open(path.join(dir,'library.sqlite'),path.join(dir,'media'));try{assert.equal(reopened.localReconcile.state().pending,1);assert.deepEqual(await reopened.reconcilePending(),[]);assert.equal(reopened.download('1').path,completed);assert.equal(reopened.localReconcile.state().pending,0);}finally{reopened.close();}store.close=()=>{};
});
test('reverse membership queries use the work index and order remains unchanged',async t=>{const {store}=await fixture(t);store.upsertWork(raw('1'));store.ingestMembers('__all__',['1'],true);const plan=store.rows('EXPLAIN QUERY PLAN SELECT collection_id FROM members WHERE work_id=? AND collection_id<>?',['1','__all__']);assert.ok(plan.some(r=>r.detail.includes('members_work')));assert.deepEqual(store.orderedMemberRows('__all__').map(r=>r.work_id),['1']);});
