import {app,session,BaseWindow} from 'electron';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
app.disableHardwareAcceleration();const profile=process.env.CANGXIA_LOCAL_TEST_PROFILE;if(!profile)throw new Error('Use isolated test runner');let started=false;const checks=[];const deadline=setTimeout(()=>{console.error('native local timeout');app.exit(1);},60000);
app.on('browser-window-created',(_e,win)=>{if(started)return;started=true;win.webContents.once('did-finish-load',()=>{void(async()=>{
 const check=(name,value)=>{assert.ok(value,name);checks.push(name);};const call=(name,...args)=>win.webContents.executeJavaScript(`window.cangxia[${JSON.stringify(name)}](...${JSON.stringify(args)})`);const raw=id=>({aweme_id:id,desc:'native '+id,author:{nickname:'fixture'},video:{play_addr:{url_list:[]}}});
 try{
 let state=await call('state');check('native SQLite opens existing records in an isolated profile',state.works.length===1200&&app.getPath('userData')===profile);const title=await win.webContents.executeJavaScript('document.title');check('title and settings identify local edition 0.2.4',state.version==='0.2.4'&&title.includes('本地版 v0.2.4')&&title===win.getTitle());
 const http=session.fromPartition('cangxia-http'),original=http.fetch,cursors=[];let blocked=true;
 http.fetch=async(url,options)=>{const route=new URL(url).pathname;if(route==='/aweme/v1/web/user/profile/self/')return new Response(JSON.stringify({status_code:0,user:{uid:'123',nickname:'fixture'}}));if(route==='/aweme/v1/web/aweme/listcollection/'){const cursor=new URLSearchParams(options.body).get('cursor');cursors.push(cursor);if(cursor==='0')return new Response(JSON.stringify({status_code:0,aweme_list:[raw('9001'),raw('9002')],has_more:1,cursor:'30'}));if(blocked)return new Response('expired',{status:401});return new Response(JSON.stringify({status_code:0,aweme_list:[raw('9003')],has_more:0,cursor:'60'}));}throw new Error('Unexpected network call');};
 const login=path.join(path.dirname(profile),'login.json');await assert.rejects(call('importLoginConfig',login));state=await call('state');check('legacy library requests explicit original-account confirmation',state.collector.pendingAccount?.uid==='123'&&!state.collector.connected);await call('confirmLegacyAccount',state.collector.pendingAccount.token);
 await call('sync',{readAll:true,maxNew:100000});let end=Date.now()+10000;do{await new Promise(r=>setTimeout(r,100));state=await call('state');}while(state.collector.busy&&Date.now()<end);
 check('access failure stops reading and preserves the committed page',state.works.length===1202&&state.collector.needsLogin&&!state.collector.connected&&state.syncProgress[0]?.canResume);
 await new Promise(r=>setTimeout(r,500));check('incremental IPC refreshes the visible first card',await win.webContents.executeJavaScript(`document.querySelector('.cover-title').textContent==='native 9001'`));check('verification action is visible without clearing data',await win.webContents.executeJavaScript(`document.body.innerText.includes('重新登录 / 完成验证')`));
 blocked=false;await call('importLoginConfig',login);await call('sync',{readAll:true,maxNew:100000,resume:true});end=Date.now()+10000;do{await new Promise(r=>setTimeout(r,100));state=await call('state');}while(state.collector.busy&&Date.now()<end);check('relogin resumes the saved cursor without repeating the first page',JSON.stringify(cursors)===JSON.stringify(['0','30','30'])&&state.works.length===1203);http.fetch=original;
 const log=fs.readFileSync(path.join(profile,'diagnostics','events.jsonl'),'utf8');check('diagnostics record status without cookie values',log.includes('api-error')&&log.includes('401')&&!log.includes('SYNTHETIC_LOCAL_ONLY'));
 await win.webContents.executeJavaScript(`document.querySelector('[aria-label="设置"]').click()`);await new Promise(r=>setTimeout(r,200));check('settings exposes local diagnostics',await win.webContents.executeJavaScript(`document.querySelector('.modal').innerText.includes('打开诊断目录')`));
 const qrProfile=session.fromPartition('persist:cangxia-popup-login');let verificationLoads=0,ordinaryLogin=true;
 qrProfile.protocol.handle('https',request=>{if(new URL(request.url).pathname!=='/user/self')return new Response('',{status:404});verificationLoads++;if(ordinaryLogin)return new Response('<!doctype html><html><body><h2>登录后即可观看喜欢、收藏的视频</h2><div>扫码登录</div><canvas id="qrcode" width="180" height="180"></canvas><div>验证码登录 密码登录</div><input placeholder="请输入手机号"><input placeholder="请输入验证码" autocomplete="one-time-code"><button>获取验证码</button><script>const c=document.querySelector("canvas").getContext("2d");c.fillStyle="white";c.fillRect(0,0,180,180);c.fillStyle="black";for(let i=0;i<18;i++)for(let j=0;j<18;j++)if((i+j)%2)c.fillRect(i*10,j*10,10,10);</script></body></html>',{headers:{'content-type':'text/html; charset=utf-8'}});return new Response('<!doctype html><html><head><style>body{margin:0;background:#f2f5f8;font-family:sans-serif;display:grid;place-items:center;height:100vh}.card{background:white;padding:40px;border-radius:16px;width:480px}input{display:block;width:100%;padding:14px;box-sizing:border-box;margin:20px 0}h2{color:#263344}small{color:#778899}</style></head><body><div class="card"><h2>身份验证</h2><p>测试验证页面（仅合成数据，无真实账号）</p><p>接收短信验证码</p><input id="code" placeholder="短信验证码" autocomplete="one-time-code"><small>用于验证内嵌窗口保持会话，不会发送短信。</small></div></body></html>',{headers:{'content-type':'text/html; charset=utf-8'}});});
 await win.webContents.executeJavaScript(`document.querySelector('[aria-label="关闭弹窗"]').click();document.querySelector('.account-button').click()`);
 end=Date.now()+8000;do{await new Promise(r=>setTimeout(r,100));state=await call('state');}while(state.qr.phase!=='ready'&&Date.now()<end);
 check('ordinary QR plus SMS form stays compact without embedding the webpage',state.qr.phase==='ready'&&!!state.qr.image&&!state.qr.inline&&!win.contentView.children.some(v=>v.webContents&&v.webContents!==win.webContents));
 end=Date.now()+5000;let qrVisible=false;do{await new Promise(r=>setTimeout(r,100));qrVisible=await win.webContents.executeJavaScript(`!!document.querySelector('.qr-image-box img')?.naturalWidth`);}while(!qrVisible&&Date.now()<end);check('compact login modal renders the extracted QR image',qrVisible);
 fs.writeFileSync('.test-output/compact-qr-fixture.png',(await win.webContents.capturePage()).toPNG());
 await win.webContents.executeJavaScript(`document.querySelector('[aria-label="关闭弹窗"]').click()`);await new Promise(r=>setTimeout(r,200));ordinaryLogin=false;
 await win.webContents.executeJavaScript(`document.querySelector('.account-button').click()`);
 const inlineViews=()=>win.contentView.children.flatMap(v=>[v,...v.children]);let embedded;end=Date.now()+8000;do{await new Promise(r=>setTimeout(r,100));embedded=inlineViews().find(v=>v.webContents&&v.webContents!==win.webContents);}while(!embedded&&Date.now()<end);
 check('SMS verification embeds a sandboxed official-page view inside the modal',!!embedded&&embedded.getBounds().width>200&&embedded.getBounds().height>100&&embedded.webContents.getLastWebPreferences().sandbox&&embedded.webContents.getLastWebPreferences().contextIsolation);
 const crop=win.contentView.children.find(v=>v.children.includes(embedded));check('only the verification card is mounted in a compact native clipping view',!!crop&&crop.getBounds().width<=500&&embedded.getBounds().x<0&&embedded.getBounds().y<0&&await win.webContents.executeJavaScript(`document.querySelector('.modal').getBoundingClientRect().width<=560`));
 const pageContents=embedded.webContents,pageId=pageContents.id;await embedded.webContents.executeJavaScript(`document.querySelector('#code').value='synthetic-input';window.fixtureState='preserved'`);
 check('verification page has no application IPC or Node access',await embedded.webContents.executeJavaScript(`typeof window.cangxia==='undefined'&&typeof require==='undefined'`));
 await assert.rejects(call('setQrPageBounds',pageId,{x:0,y:0,width:1000,height:2000}));
 await call('showQrExternalPage');check('detached fallback reuses the same WebContents',!inlineViews().includes(embedded)&&BaseWindow.getAllWindows().some(w=>w.id!==win.id&&w.isVisible()));
 await call('showQrLoginPage');end=Date.now()+5000;while(!inlineViews().includes(embedded)&&Date.now()<end)await new Promise(r=>setTimeout(r,100));
 check('returning inline preserves page state and synthetic input without reloading',inlineViews().includes(embedded)&&verificationLoads===2&&await embedded.webContents.executeJavaScript(`window.fixtureState==='preserved'&&document.querySelector('#code').value==='synthetic-input'`));
 await embedded.webContents.executeJavaScript(`window.fixtureCard=document.querySelector('.card');window.fixtureCard.remove()`);await new Promise(r=>setTimeout(r,900));check('unrecognized page hides the crop instead of exposing the surrounding website',!crop.getVisible());
 await embedded.webContents.executeJavaScript(`document.body.append(window.fixtureCard)`);await new Promise(r=>setTimeout(r,900));check('verification panel can return without replacing the official input',crop.getVisible()&&await embedded.webContents.executeJavaScript(`document.querySelector('#code').value==='synthetic-input'`));
 const cb=crop.getBounds(),pb=embedded.getBounds();try{fs.writeFileSync('.test-output/inline-verification-fixture.png',(await embedded.webContents.capturePage({x:-pb.x,y:-pb.y,width:cb.width,height:cb.height})).toPNG());}catch{}
 await win.webContents.executeJavaScript(`document.querySelector('[aria-label="关闭弹窗"]').click()`);await new Promise(r=>setTimeout(r,200));check('closing the modal destroys its page and hidden host',pageContents.isDestroyed()&&BaseWindow.getAllWindows().length===1);qrProfile.protocol.unhandle('https');
 fs.mkdirSync('.test-output',{recursive:true});try{fs.writeFileSync('.test-output/local-desktop.png',(await win.webContents.capturePage()).toPNG());}catch{}fs.writeFileSync('.test-output/local-desktop-result.json',JSON.stringify({ok:true,checks},null,2));console.log({ok:true,checks});clearTimeout(deadline);app.quit();
 }catch(e){console.error(e);fs.writeFileSync('.test-output/local-desktop-result.json',JSON.stringify({ok:false,error:e.stack,checks},null,2));clearTimeout(deadline);app.exit(1);}
})();});});
await import(process.env.CANGXIA_LOCAL_TEST_MAIN?pathToFileURL(path.resolve(process.env.CANGXIA_LOCAL_TEST_MAIN)).href:'../electron/main.mjs');
