import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {DatabaseSync} from 'node:sqlite';
import {Store} from '../electron/store.mjs';import {SnapshotFeed} from '../electron/snapshot-feed.mjs';import {mergeState,arrayPatch} from '../electron/state-patch.mjs';
const raw=id=>({aweme_id:id,desc:'fixture '+id,author:{nickname:'fixture'},video:{play_addr:{url_list:['https://v3.douyinvod.com/'+('x'.repeat(4000))+'.mp4']},cover:{url_list:['https://p3.douyinpic.com/'+('x'.repeat(2000))+'.jpg']}}});
async function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-local-test-'));const store=await Store.open(path.join(dir,'library.sqlite'),path.join(dir,'media'));t.after(()=>{try{store.close();}catch{}assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true,maxRetries:3,retryDelay:100});});return {dir,store};}
test('native database preserves legacy SQLite and writes commits without replacing the database file',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-legacy-test-'));t.after(()=>{assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true});});const file=path.join(dir,'library.sqlite');const old=new DatabaseSync(file);old.exec('CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)');old.prepare('INSERT INTO settings VALUES(?,?)').run('fixture','"original"');old.close();const original=fs.readFileSync(file);const store=await Store.open(file,path.join(dir,'media'));
 try{const preserved=new DatabaseSync(file+'.pre-local-0.2.0',{readOnly:true});try{assert.equal(preserved.prepare("SELECT value FROM settings WHERE key='fixture'").get().value,'"original"');assert.equal(preserved.prepare('PRAGMA quick_check').get().quick_check,'ok');}finally{preserved.close();}const identity=fs.statSync(file).ino;store.setSetting('fixture','changed');store.save();assert.equal(fs.statSync(file).ino,identity);assert.equal(fs.existsSync(file+'.tmp'),false);assert.equal(store.getSetting('fixture'),'changed');}finally{store.close();}
});
test('page and cursor commit atomically and a reopened store resumes the next cursor',async t=>{
 const f=await fixture(t),s=f.store;let run=s.sync.start('__all__',{readAll:true});s.sync.applyPage(run,[raw('3'),raw('2')],{next:'30',complete:false});assert.equal(s.sync.get('__all__').nextCursor,'30');s.db.connection.close();
 const reopened=await Store.open(path.join(f.dir,'library.sqlite'),path.join(f.dir,'media'));try{assert.deepEqual(reopened.snapshot().members.__all__,['3','2']);assert.equal(reopened.sync.list()[0].canResume,true);run=reopened.sync.start('__all__',{resume:true,readAll:true});assert.equal(run.nextCursor,'30');reopened.sync.applyPage(run,[raw('1')],{next:'60',complete:true});assert.deepEqual(reopened.snapshot().members.__all__,['3','2','1']);assert.equal(reopened.sync.list().length,0);}finally{reopened.close();}
});
test('invalid page rolls back its records and cursor; partial page resumes that page without skipping items',async t=>{
 const {store:s}=await fixture(t);const run=s.sync.start('__all__');assert.throws(()=>s.sync.applyPage(run,[raw('3'),raw('bad')],{next:'30',complete:false}));assert.equal(s.work('3'),null);assert.equal(s.sync.get('__all__').nextCursor,'0');
 s.sync.applyPage(run,[raw('3'),raw('2')],{next:'30',complete:false},{maxNew:1});assert.equal(run.nextCursor,'0');s.sync.finish(run,false);const resumed=s.sync.start('__all__',{resume:true,readAll:true});s.sync.applyPage(resumed,[raw('3'),raw('2')],{next:'30',complete:true});assert.deepEqual(s.snapshot().members.__all__,['3','2']);
});
test('large snapshot sends changed records and array patches instead of full records on each progress update',async t=>{
 const {store:s}=await fixture(t);s.db.run('BEGIN');const ids=[];for(let i=1;i<=3000;i++){const id=String(i);ids.push(id);s.upsertWork(raw(id));}s.ingestMembers('__all__',ids,true);s.db.run('COMMIT');const feed=new SnapshotFeed(s);let state=feed.frame({collector:{busy:false}},{full:true});const fullBytes=Buffer.byteLength(JSON.stringify(state));assert.equal(state.works[0].thumbnail,undefined);
 const status=feed.frame({collector:{busy:true}});assert.equal(status.changedWorks,undefined);assert.ok(Buffer.byteLength(JSON.stringify(status))<1000);
 const w=s.work('1');s.put('works','1',{...w,name:'changed'});s.save();const patch=feed.frame({collector:{busy:false}});assert.equal(patch.changedWorks.length,1);assert.ok(Buffer.byteLength(JSON.stringify(patch))<fullBytes/20);state=mergeState(state,patch);assert.equal(state.works[0].name,'changed');assert.equal(state.works.length,3000);
 s.ingestMembers('__all__',['3000','2','1'],true);const move=feed.frame({});state=mergeState(state,move);assert.deepEqual(state.members.__all__,['3000','2','1']);
});
test('membership splice handles prefix insertion, deletion and no change',()=>{for(const [a,b]of [[['1','2'],['3','1','2']],[['1','2','3'],['1','3']],[[],['1']],[['1'],[]]]){const p=arrayPatch(a,b);assert.deepEqual([...a.slice(0,p.start),...p.insert,...a.slice(p.start+p.remove)],b);}assert.equal(arrayPatch(['1'],['1']),null);});
test('full state queries do not consume broadcast changes and stale patches never duplicate membership',async t=>{const {store:s}=await fixture(t);s.upsertWork(raw('1'));s.ingestMembers('__all__',['1'],true);const feed=new SnapshotFeed(s),initial=feed.frame({},{full:true});s.upsertWork(raw('2'));s.ingestMembers('__all__',['2','1'],true);const current=feed.frame({},{full:true});const delta=feed.frame({});assert.deepEqual(mergeState(initial,delta).members.__all__,['2','1']);assert.deepEqual(mergeState(current,delta).members.__all__,['2','1']);const behind={...initial,libraryRevision:initial.libraryRevision+1};assert.equal(mergeState(behind,delta).needsFullState,true);});
