import {app,session} from 'electron';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
app.disableHardwareAcceleration();const profile=process.env.CANGXIA_LOCAL_TEST_PROFILE;if(!profile)throw new Error('Use isolated test runner');let started=false;const checks=[];const deadline=setTimeout(()=>{console.error('native local timeout');app.exit(1);},60000);
app.on('browser-window-created',(_e,win)=>{if(started)return;started=true;win.webContents.once('did-finish-load',()=>{void(async()=>{
 const check=(name,value)=>{assert.ok(value,name);checks.push(name);};const call=(name,...args)=>win.webContents.executeJavaScript(`window.cangxia[${JSON.stringify(name)}](...${JSON.stringify(args)})`);const raw=id=>({aweme_id:id,desc:'native '+id,author:{nickname:'fixture'},video:{play_addr:{url_list:[]}}});
 try{
 let state=await call('state');check('native SQLite opens existing records in an isolated profile',state.works.length===1200&&app.getPath('userData')===profile);const title=await win.webContents.executeJavaScript('document.title');check('title and settings identify local edition 0.2.1',state.version==='0.2.1'&&title.includes('本地版 v0.2.1')&&title===win.getTitle());
 const http=session.fromPartition('cangxia-http'),original=http.fetch,cursors=[];let blocked=true;
 http.fetch=async(url,options)=>{const route=new URL(url).pathname;if(route==='/aweme/v1/web/user/profile/self/')return new Response(JSON.stringify({status_code:0,user:{uid:'123',nickname:'fixture'}}));if(route==='/aweme/v1/web/aweme/listcollection/'){const cursor=new URLSearchParams(options.body).get('cursor');cursors.push(cursor);if(cursor==='0')return new Response(JSON.stringify({status_code:0,aweme_list:[raw('9001'),raw('9002')],has_more:1,cursor:'30'}));if(blocked)return new Response('expired',{status:401});return new Response(JSON.stringify({status_code:0,aweme_list:[raw('9003')],has_more:0,cursor:'60'}));}throw new Error('Unexpected network call');};
 const login=path.join(path.dirname(profile),'login.json');await assert.rejects(call('importLoginConfig',login));state=await call('state');check('legacy library requests explicit original-account confirmation',state.collector.pendingAccount?.uid==='123'&&!state.collector.connected);await call('confirmLegacyAccount',state.collector.pendingAccount.token);
 await call('sync',{readAll:true,maxNew:100000});let end=Date.now()+10000;do{await new Promise(r=>setTimeout(r,100));state=await call('state');}while(state.collector.busy&&Date.now()<end);
 check('access failure stops reading and preserves the committed page',state.works.length===1202&&state.collector.needsLogin&&!state.collector.connected&&state.syncProgress[0]?.canResume);
 await new Promise(r=>setTimeout(r,500));check('incremental IPC refreshes the visible first card',await win.webContents.executeJavaScript(`document.querySelector('.cover-title').textContent==='native 9001'`));check('verification action is visible without clearing data',await win.webContents.executeJavaScript(`document.body.innerText.includes('重新登录 / 完成验证')`));
 blocked=false;await call('importLoginConfig',login);await call('sync',{readAll:true,maxNew:100000,resume:true});end=Date.now()+10000;do{await new Promise(r=>setTimeout(r,100));state=await call('state');}while(state.collector.busy&&Date.now()<end);check('relogin resumes the saved cursor without repeating the first page',JSON.stringify(cursors)===JSON.stringify(['0','30','30'])&&state.works.length===1203);http.fetch=original;
 const log=fs.readFileSync(path.join(profile,'diagnostics','events.jsonl'),'utf8');check('diagnostics record status without cookie values',log.includes('api-error')&&log.includes('401')&&!log.includes('SYNTHETIC_LOCAL_ONLY'));
 await win.webContents.executeJavaScript(`document.querySelector('[aria-label="设置"]').click()`);await new Promise(r=>setTimeout(r,200));check('settings exposes local diagnostics',await win.webContents.executeJavaScript(`document.querySelector('.modal').innerText.includes('打开诊断目录')`));
 fs.mkdirSync('.test-output',{recursive:true});try{fs.writeFileSync('.test-output/local-desktop.png',(await win.webContents.capturePage()).toPNG());}catch{}fs.writeFileSync('.test-output/local-desktop-result.json',JSON.stringify({ok:true,checks},null,2));console.log({ok:true,checks});clearTimeout(deadline);app.quit();
 }catch(e){console.error(e);fs.writeFileSync('.test-output/local-desktop-result.json',JSON.stringify({ok:false,error:e.stack,checks},null,2));clearTimeout(deadline);app.exit(1);}
})();});});
await import(process.env.CANGXIA_LOCAL_TEST_MAIN?pathToFileURL(path.resolve(process.env.CANGXIA_LOCAL_TEST_MAIN)).href:'../electron/main.mjs');
