import {app,session,BaseWindow} from 'electron';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
app.disableHardwareAcceleration();const profile=process.env.CANGXIA_LOCAL_TEST_PROFILE;if(!profile)throw new Error('Use isolated test runner');let started=false;const checks=[];const deadline=setTimeout(()=>{console.error('native local timeout');app.exit(1);},60000);
app.on('browser-window-created',(_e,win)=>{if(started)return;started=true;win.webContents.once('did-finish-load',()=>{void(async()=>{
 const check=(name,value)=>{assert.ok(value,name);checks.push(name);};const call=(name,...args)=>win.webContents.executeJavaScript(`window.cangxia[${JSON.stringify(name)}](...${JSON.stringify(args)})`);const raw=id=>({aweme_id:id,desc:'native '+id,author:{nickname:'fixture'},video:{play_addr:{url_list:[]}}});
 try{
 let state=await call('state');check('native SQLite opens existing records in an isolated profile',state.works.length===1200&&app.getPath('userData')===profile);const title=await win.webContents.executeJavaScript('document.title');check('title and settings identify local edition 0.2.2',state.version==='0.2.2'&&title.includes('本地版 v0.2.2')&&title===win.getTitle());
 const http=session.fromPartition('cangxia-http'),original=http.fetch,cursors=[];let blocked=true;
 http.fetch=async(url,options)=>{const route=new URL(url).pathname;if(route==='/aweme/v1/web/user/profile/self/')return new Response(JSON.stringify({status_code:0,user:{uid:'123',nickname:'fixture'}}));if(route==='/aweme/v1/web/aweme/listcollection/'){const cursor=new URLSearchParams(options.body).get('cursor');cursors.push(cursor);if(cursor==='0')return new Response(JSON.stringify({status_code:0,aweme_list:[raw('9001'),raw('9002')],has_more:1,cursor:'30'}));if(blocked)return new Response('expired',{status:401});return new Response(JSON.stringify({status_code:0,aweme_list:[raw('9003')],has_more:0,cursor:'60'}));}throw new Error('Unexpected network call');};
 const login=path.join(path.dirname(profile),'login.json');await assert.rejects(call('importLoginConfig',login));state=await call('state');check('legacy library requests explicit original-account confirmation',state.collector.pendingAccount?.uid==='123'&&!state.collector.connected);await call('confirmLegacyAccount',state.collector.pendingAccount.token);
 await call('sync',{readAll:true,maxNew:100000});let end=Date.now()+10000;do{await new Promise(r=>setTimeout(r,100));state=await call('state');}while(state.collector.busy&&Date.now()<end);
 check('access failure stops reading and preserves the committed page',state.works.length===1202&&state.collector.needsLogin&&!state.collector.connected&&state.syncProgress[0]?.canResume);
 await new Promise(r=>setTimeout(r,500));check('incremental IPC refreshes the visible first card',await win.webContents.executeJavaScript(`document.querySelector('.cover-title').textContent==='native 9001'`));check('verification action is visible without clearing data',await win.webContents.executeJavaScript(`document.body.innerText.includes('重新登录 / 完成验证')`));
 blocked=false;await call('importLoginConfig',login);await call('sync',{readAll:true,maxNew:100000,resume:true});end=Date.now()+10000;do{await new Promise(r=>setTimeout(r,100));state=await call('state');}while(state.collector.busy&&Date.now()<end);check('relogin resumes the saved cursor without repeating the first page',JSON.stringify(cursors)===JSON.stringify(['0','30','30'])&&state.works.length===1203);http.fetch=original;
 const log=fs.readFileSync(path.join(profile,'diagnostics','events.jsonl'),'utf8');check('diagnostics record status without cookie values',log.includes('api-error')&&log.includes('401')&&!log.includes('SYNTHETIC_LOCAL_ONLY'));
 await win.webContents.executeJavaScript(`document.querySelector('[aria-label="设置"]').click()`);await new Promise(r=>setTimeout(r,200));check('settings exposes local diagnostics',await win.webContents.executeJavaScript(`document.querySelector('.modal').innerText.includes('打开诊断目录')`));
 const qrProfile=session.fromPartition('persist:cangxia-popup-login');let verificationLoads=0;
 qrProfile.protocol.handle('https',request=>{if(new URL(request.url).pathname!=='/user/self')return new Response('',{status:404});verificationLoads++;return new Response('<!doctype html><html><head><style>body{margin:0;background:#f2f5f8;font-family:sans-serif;display:grid;place-items:center;height:100vh}.card{background:white;padding:40px;border-radius:16px;width:480px}input{display:block;width:100%;padding:14px;box-sizing:border-box;margin:20px 0}h2{color:#263344}small{color:#778899}</style></head><body><div class="card"><h2>身份验证</h2><p>测试验证页面（仅合成数据，无真实账号）</p><p>接收短信验证码</p><input id="code" placeholder="短信验证码" autocomplete="one-time-code"><small>用于验证内嵌窗口保持会话，不会发送短信。</small></div></body></html>',{headers:{'content-type':'text/html; charset=utf-8'}});});
 await win.webContents.executeJavaScript(`document.querySelector('[aria-label="关闭弹窗"]').click();document.querySelector('.account-button').click()`);
 let embedded;end=Date.now()+8000;do{await new Promise(r=>setTimeout(r,100));embedded=win.contentView.children.find(v=>v.webContents&&v.webContents!==win.webContents);}while(!embedded&&Date.now()<end);
 check('SMS verification embeds a sandboxed official-page view inside the modal',!!embedded&&embedded.getBounds().width>200&&embedded.getBounds().height>100&&embedded.webContents.getLastWebPreferences().sandbox&&embedded.webContents.getLastWebPreferences().contextIsolation);
 const pageContents=embedded.webContents,pageId=pageContents.id;await embedded.webContents.executeJavaScript(`document.querySelector('#code').value='synthetic-input';window.fixtureState='preserved'`);
 check('verification page has no application IPC or Node access',await embedded.webContents.executeJavaScript(`typeof window.cangxia==='undefined'&&typeof require==='undefined'`));
 await assert.rejects(call('setQrPageBounds',pageId,{x:0,y:0,width:1000,height:2000}));
 await call('showQrExternalPage');check('detached fallback reuses the same WebContents',!win.contentView.children.includes(embedded)&&BaseWindow.getAllWindows().some(w=>w.id!==win.id&&w.isVisible()));
 await call('showQrLoginPage');end=Date.now()+5000;while(!win.contentView.children.includes(embedded)&&Date.now()<end)await new Promise(r=>setTimeout(r,100));
 check('returning inline preserves page state and synthetic input without reloading',win.contentView.children.includes(embedded)&&verificationLoads===1&&await embedded.webContents.executeJavaScript(`window.fixtureState==='preserved'&&document.querySelector('#code').value==='synthetic-input'`));
 try{fs.writeFileSync('.test-output/inline-verification-fixture.png',(await embedded.webContents.capturePage()).toPNG());}catch{}
 await win.webContents.executeJavaScript(`document.querySelector('[aria-label="关闭弹窗"]').click()`);await new Promise(r=>setTimeout(r,200));check('closing the modal destroys its page and hidden host',pageContents.isDestroyed()&&BaseWindow.getAllWindows().length===1);qrProfile.protocol.unhandle('https');
 fs.mkdirSync('.test-output',{recursive:true});try{fs.writeFileSync('.test-output/local-desktop.png',(await win.webContents.capturePage()).toPNG());}catch{}fs.writeFileSync('.test-output/local-desktop-result.json',JSON.stringify({ok:true,checks},null,2));console.log({ok:true,checks});clearTimeout(deadline);app.quit();
 }catch(e){console.error(e);fs.writeFileSync('.test-output/local-desktop-result.json',JSON.stringify({ok:false,error:e.stack,checks},null,2));clearTimeout(deadline);app.exit(1);}
})();});});
await import(process.env.CANGXIA_LOCAL_TEST_MAIN?pathToFileURL(path.resolve(process.env.CANGXIA_LOCAL_TEST_MAIN)).href:'../electron/main.mjs');
