import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {Collector} from '../electron/account-collector.mjs';import {Store} from '../electron/store.mjs';import {AuthVault} from '../electron/auth-data.mjs';import {SystemBrowser} from '../electron/system-browser.mjs';
const auth={source:'popup',userAgent:'Fixture/1',cookies:[{name:'sessionid',value:'SYNTHETIC',domain:'.douyin.com'}]},raw=id=>({aweme_id:id,desc:'keep',author:{nickname:'fixture'}});
async function setup(t,fetcher){const root=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-logout-')),store=await Store.open(path.join(root,'library.sqlite'),path.join(root,'media'));let cookies=[];const profile={setUserAgent(){},clearStorageData:async()=>{cookies=[];},cookies:{set:async c=>cookies.push(c),get:async()=>cookies},fetch:fetcher};const vault=new AuthVault(path.join(root,'login-state.bin'),{isEncryptionAvailable:()=>true,encryptString:x=>Buffer.from(x),decryptString:x=>x.toString()});const browser={on(){},close:async()=>{},clearLoginData:async()=>{}};const c=new Collector(store,()=>{},{profile,vault,browser,verifyIdentity:async()=>({uid:'123',nickname:'fixture'}),delay:async()=>{}});await c.ready;await c.applyAuth(auth);t.after(()=>{store.close();assert.equal(path.dirname(root),os.tmpdir());fs.rmSync(root,{recursive:true,force:true});});return {root,store,profile,vault,browser,c};}
test('logout clears authentication and keeps account binding, works, tags and read checkpoint',async t=>{
 const f=await setup(t,async()=>new Response('{}'));f.store.upsertWork(raw('1'));f.store.put('local_tags','1',{id:'1',tags:['keep']});const run=f.store.sync.start('__all__',{readAll:true});f.store.sync.applyPage(run,[raw('1')],{items:[raw('1')],next:'30',complete:false},{maxNew:Infinity});f.store.sync.finish(run,false);
 await f.c.logout();assert.equal(f.c.status.connected,false);assert.equal(f.store.getSetting('loggedOut'),true);assert.equal(f.store.getSetting('browserAccountKey'),'uid:123');assert.equal(f.store.all('works').length,1);assert.deepEqual(f.store.get('local_tags','1').tags,['keep']);assert.equal(f.store.sync.get('__all__').nextCursor,'30');assert.equal((await f.profile.cookies.get()).length,0);assert.ok(!fs.existsSync(f.vault.file));
 let loaded=false;const next=new Collector(f.store,()=>{},{profile:f.profile,browser:f.browser,vault:{load(){loaded=true;}},verifyIdentity:async()=>({uid:'123'})});await next.ready;assert.equal(loaded,false);
 f.c.verifyIdentity=async()=>({uid:'456'});await assert.rejects(f.c.applyAuth(auth),e=>e.code==='ACCOUNT_MISMATCH');assert.equal(f.store.getSetting('loggedOut'),true);
 f.c.verifyIdentity=async()=>({uid:'123'});await f.c.applyAuth(auth);assert.equal(f.store.getSetting('loggedOut'),false);
});
test('late authentication cannot recreate saved credentials after logout',async t=>{
 const f=await setup(t,async()=>new Response('{}'));let started;const ready=new Promise(r=>started=r);f.c.verifyIdentity=async(_p,_u,{signal})=>{started();return new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true}));};const pending=f.c.applyAuth(auth);pending.catch(()=>{});await ready;await f.c.logout();await assert.rejects(pending);assert.ok(!fs.existsSync(f.vault.file));assert.equal(f.c.status.connected,false);
});
test('cleanup failure still disables automatic login',async t=>{const f=await setup(t,async()=>new Response('{}'));f.browser.clearLoginData=async()=>{throw Error('locked');};await assert.rejects(f.c.logout());assert.equal(f.store.getSetting('loggedOut'),true);assert.equal(f.c.status.connected,false);assert.equal(f.c.status.logoutIncomplete,true);});
test('progress counts new items toward quota while counting all checked works separately',async t=>{const f=await setup(t,async()=>new Response(JSON.stringify({status_code:0,aweme_list:['1','2','3','4'].map(raw),has_more:1,cursor:'30'})));f.store.upsertWork(raw('1'));f.store.upsertWork(raw('2'));await f.c.sync({maxNew:2});assert.equal(f.c.status.readProgress.goal,2);assert.equal(f.c.status.readProgress.added,2);assert.equal(f.c.status.readProgress.checked,4);assert.equal(f.c.status.readProgress.stage,'finished');});
test('stopping before authentication readiness cannot start a later read',async t=>{let calls=0;const f=await setup(t,async()=>{calls++;return new Response('{}');});let release;f.c.isAuthenticated=async()=>{await new Promise(r=>release=r);return true;};const pending=f.c.sync();await new Promise(r=>setImmediate(r));f.c.stop();release();await pending;assert.equal(calls,0);assert.equal(f.c.busy,false);});
test('browser logout removes only its own chrome and edge directories',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-profile-clean-'));t.after(()=>{assert.equal(path.dirname(root),os.tmpdir());fs.rmSync(root,{recursive:true,force:true});});const own=path.join(root,'system-browser'),other=path.join(root,'ordinary-browser');for(const dir of [path.join(own,'chrome'),path.join(own,'edge'),other]){fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'keep.txt'),'synthetic');}const b=new SystemBrowser(own);await b.clearLoginData();assert.ok(fs.existsSync(path.join(other,'keep.txt')));assert.ok(!fs.existsSync(path.join(own,'chrome')));});
