import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {randomBytes,randomUUID} from 'node:crypto';
import {createBackupServer} from '../backup-server/server.mjs';import {BackupClient} from '../electron/backup-client.mjs';import {Store} from '../electron/store.mjs';import {NASRemoval} from '../electron/nas-removal.mjs';
import {contentHash} from '../shared/backup-protocol.mjs';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==','base64'),vault={seal:s=>Buffer.from(s).toString('base64'),open:s=>Buffer.from(s,'base64').toString()};
async function fixture(t){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'cx-nas-remove-'));let service=createBackupServer({dataDir:path.join(root,'server'),token:'fixture-access-token-1234567890',allowInsecureLoopback:true});const address=await service.listen(),clients=[];
 async function client(name,seed=false){const profile=path.join(root,name),store=await Store.open(path.join(profile,'library.sqlite'),path.join(profile,'media'));if(seed){for(const id of ['1','2','3']){store.upsertWork({aweme_id:id,desc:'work '+id,images:[{url_list:['https://p3.douyinpic.com/'+id+'.png']}]});const dir=store.destination(id).dir;fs.mkdirSync(dir,{recursive:true});const bytes=id==='3'?Buffer.concat([png,Buffer.from('unique')]):png;fs.writeFileSync(path.join(dir,'image.png'),bytes);fs.writeFileSync(path.join(dir,'info.json'),'{}');store.put('downloads',id,{id,path:dir,state:'complete',collectionId:'__all__',assets:[{key:'image-0',file:'image.png',kind:'image',size:bytes.length},{key:'metadata',file:'info.json',kind:'metadata',size:2}]});}store.ingestMembers('__all__',['3','2','1'],true);}
  const c=new BackupClient(store,profile,{vault,heartbeatMs:60000});clients.push(c);await c.configure({url:'http://127.0.0.1:'+address.port,token:'fixture-access-token-1234567890',deviceName:name,intervalMinutes:60});c.fetchCover=async()=>{throw Error('unexpected online preview');};return c;
 }
 t.after(async()=>{for(const c of clients){await c.close();c.store.close();}await service.close();assert.equal(path.dirname(root),os.tmpdir());fs.rmSync(root,{recursive:true,force:true});});return {root,get service(){return service;},client,async restart(){await service.close();service=createBackupServer({dataDir:path.join(root,'server'),token:'fixture-access-token-1234567890',allowInsecureLoopback:true});await service.listen(address.port);}};
}
test('delete local media then NAS never fetches online previews or recreates the deleted copy',async t=>{
 const f=await fixture(t),a=await f.client('A',true);await a.sync();const sha=a.store.get('backup_downloads','3').assets[0].sha256;
 fs.rmSync(a.store.download('3').path,{recursive:true});a.store.db.run('DELETE FROM downloads WHERE id=?',['3']);a.store.invalidateViews();a.store.save();let requests=0;a.fetchCover=async()=>{requests++;throw Error('must not fetch deleted preview');};
 await a.backupAction('delete',['3']);await a.automaticSync();await a.sync();assert.equal(requests,0);assert.equal(a.status.pendingCovers,0);assert.equal(a.store.snapshot().works.find(w=>w.id==='3').backedUp,false);assert.equal(fs.existsSync(path.join(f.root,'server','objects',sha)),false);assert.ok(a.store.work('3'));
});
test('service upgrade migrates old exclusions once and automatically backs up existing local media',async t=>{
 const f=await fixture(t),a=await f.client('A',true);await a.sync();await a.backupAction('delete',['3']);const row=a.store.get('backup_downloads','3'),libraryId=f.service.status().libraryId,base=f.service.status().revision;
 const legacy={...row,backupDeleted:true,deletedHashes:['a'.repeat(64)]};f.service.db.prepare("UPDATE records SET body=? WHERE kind='downloads' AND id='3'").run(JSON.stringify(legacy));a.store.put('backup_downloads','3',legacy);a.meta.baseline['downloads:3']=contentHash(legacy);await a.changed();f.service.db.prepare('INSERT INTO deleted_hashes VALUES(?,?)').run('a'.repeat(64),'3');f.service.db.exec("DELETE FROM meta WHERE key='automaticRebackupPolicy'");
 await a.release();await f.restart();assert.equal(f.service.status().libraryId,libraryId);assert.equal(f.service.status().revision,base+1);assert.equal(f.service.db.prepare('SELECT COUNT(*) n FROM deleted_hashes').get().n,0);await a.check();assert.equal(a.store.get('backup_downloads','3').backupDeleted,false);await a.automaticSync();assert.ok(a.store.snapshot().works.find(w=>w.id==='3').backedUp);
 const revision=f.service.status().revision;await a.release();await f.restart();assert.equal(f.service.status().revision,revision);
});
test('delete keeps local records, permits automatic rebackup, and protects shared objects',async t=>{
 const f=await fixture(t),a=await f.client('A',true);await a.sync();const shared=a.store.get('backup_downloads','1').assets[0].sha256,unique=a.store.get('backup_downloads','3').assets[0].sha256,before=a.store.snapshot().members.__all__;
 await a.backupAction('delete',['1']);assert.equal(a.store.get('backup_downloads','1').backupDeleted,false);assert.ok(a.store.download('1'));assert.ok(a.store.isDownloaded('1'));assert.deepEqual(a.store.snapshot().members.__all__,before);assert.equal(a.store.all('works').length,3);assert.equal(a.store.snapshot().works.find(w=>w.id==='1').backedUp,false);assert.ok(fs.existsSync(path.join(f.root,'server','objects',shared)));
 await a.automaticSync();assert.ok(a.store.snapshot().works.find(w=>w.id==='1').backedUp);assert.equal(a.status.pendingCovers,0);await a.backupAction('delete',['1']);
 const result=await a.backupAction('delete',['3']);assert.ok(result.cleanup.freedBytes>0);assert.equal(fs.existsSync(path.join(f.root,'server','objects',unique)),false);assert.ok(a.store.download('3'));await a.backupAction('delete',['2']);assert.equal(fs.existsSync(path.join(f.root,'server','objects',shared)),false);
});
test('a second PC automatically rebacks up its remaining local media',async t=>{
 const f=await fixture(t),a=await f.client('A',true);await a.sync();await a.release();const b=await f.client('B');await b.restoreWork({id:'1'},new AbortController().signal,()=>({}));await b.sync();await b.release();await a.check();await a.backupAction('delete',['1']);await a.release();await b.check();assert.equal(b.store.get('backup_downloads','1').backupDeleted,false);assert.ok(b.store.isDownloaded('1'));await b.automaticSync();assert.equal(b.status.pendingCovers,0);assert.equal(b.store.get('backup_downloads','1').backupDeleted,false);assert.equal(b.store.snapshot().works.find(w=>w.id==='1').backedUp,true);
});
test('lost deletion response recovers its receipt without duplicate revision or local file deletion',async t=>{
 const f=await fixture(t),a=await f.client('A',true);await a.sync();const json=a.transport.json.bind(a.transport);let lose=true,request;
 a.transport.json=async(method,route,options)=>{const result=await json(method,route,options);if(route==='/v1/backup-delete'&&lose){lose=false;request=options.data;throw Error('lost receipt');}return result;};await assert.rejects(a.backupAction('delete',['3']),/lost receipt/);const revision=f.service.status().revision;assert.ok(a.meta.pendingBackupAction);await a.check();assert.equal(a.meta.pendingBackupAction,undefined);assert.equal(a.store.get('backup_downloads','3').backupDeleted,false);assert.ok(a.store.isDownloaded('3'));await json('POST','/v1/backup-delete',{data:request});assert.equal(f.service.status().revision,revision);
});
test('stale deletion is rejected but media uploads remain allowed after deletion',async t=>{
 const f=await fixture(t),a=await f.client('A',true);await a.sync();const old=a.store.get('backup_downloads','1'),base=a.meta.baseRevision;await a.backupAction('delete',['1']);await assert.rejects(a.transport.json('POST','/v1/backup-delete',{data:{requestId:randomUUID(),libraryId:a.meta.libraryId,baseRevision:base,ids:['2']}}),e=>e.status===409);await assert.rejects(a.transport.json('POST','/v1/commit',{data:{requestId:randomUUID(),libraryId:a.meta.libraryId,baseRevision:a.meta.baseRevision,changes:[{table:'downloads',key:'1',body:{...old,backupDeleted:true}}]}}),/旧客户端/);assert.equal(a.store.get('backup_downloads','2').backupDeleted,undefined);
 const upload=await a.transport.json('GET','/v1/uploads/'+old.assets[0].sha256,{headers:{'x-cangxia-deletion-aware':''}});assert.ok(upload.complete);await a.sync();assert.ok(a.store.snapshot().works.find(w=>w.id==='1').backedUp);
});
test('an unaccepted stale operation is cleared by check and can be explicitly retried',async t=>{
 const f=await fixture(t),a=await f.client('A',true);await a.sync();const old=a.meta.baseRevision;await a.transport.json('POST','/v1/commit',{data:{requestId:randomUUID(),libraryId:a.meta.libraryId,baseRevision:old,changes:[{table:'local_tags',key:'2',body:{id:'2',tags:['changed elsewhere']}}]}});a.meta.pendingBackupAction={route:'/v1/backup-delete',data:{requestId:randomUUID(),libraryId:a.meta.libraryId,baseRevision:old,ids:['1']}};a.persist();await a.check();assert.equal(a.meta.pendingBackupAction,undefined);assert.equal(a.store.get('backup_downloads','1').backupDeleted,undefined);await a.backupAction('delete',['1']);assert.equal(a.store.get('backup_downloads','1').backupDeleted,false);
});
test('batch cancellation stops after the submitted batch and resumes the rest explicitly',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'cx-nas-batch-')),store=await Store.open(path.join(root,'db.sqlite'),path.join(root,'media'));t.after(()=>{store.close();fs.rmSync(root,{recursive:true,force:true});});let finish,arrived;const gate=new Promise(r=>finish=r),begun=new Promise(r=>arrived=r),calls=[];
 const backup={meta:{libraryId:'fixture'},status:{backupDeletion:true,automaticRebackup:true},assertWritable(){},cancel(){},deferSync(){},backupAction:async(action,ids)=>{calls.push(ids);if(calls.length===1){arrived();await gate;}return {count:ids.length};}};
 const task=new NASRemoval({store,backup});task.start(Array.from({length:203},(_,i)=>String(i+1)));await begun;task.cancel();finish();await task.wait();assert.equal(task.state().processed,100);assert.equal(calls.length,1);assert.equal(task.state().phase,'paused');task.start([],undefined,true);await task.wait();assert.equal(task.state().processed,203);assert.deepEqual(calls.map(x=>x.length),[100,100,3]);
});
