import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {Store} from '../electron/store.mjs';import {NasLibrary} from '../electron/nas-library.mjs';
test('unacknowledged reading resumes only on the same NAS head after reacquiring the writer lock',async()=>{
 const base=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-upgrade-')),root=path.join(base,'share');fs.mkdirSync(root);const source=await Store.open(path.join(base,'source.sqlite'),path.join(base,'media')),nas=new NasLibrary(path.join(base,'profile'));
 try{await nas.migrate(source,root);nas.deferCommits=1;const run=nas.store.sync.start('__all__',{readAll:true});nas.store.sync.applyPage(run,[{aweme_id:'234',desc:'recover',author:{nickname:'fixture'},video:{play_addr:{url_list:[]}}}],{next:'30',complete:false});nas.store.save();nas.fail('synthetic disconnect');await nas.open(root);assert.ok(nas.status.recovery);assert.ok(nas.store.work('234'));assert.equal(nas.store.syncProgress()[0].canResume,true);assert.equal(nas.store.syncProgress()[0].count,1);nas.deferCommits=0;
 }finally{await nas.close();source.close();assert.equal(path.dirname(base),os.tmpdir());fs.rmSync(base,{recursive:true,force:true,maxRetries:5,retryDelay:100});}
});
test('NAS cache retains local read cursor and logout flags across reopen without sharing them with another PC',async()=>{
 const base=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-upgrade-')),root=path.join(base,'share');fs.mkdirSync(root);const source=await Store.open(path.join(base,'source.sqlite'),path.join(base,'media')),a=new NasLibrary(path.join(base,'a')),b=new NasLibrary(path.join(base,'b'));
 try{await a.migrate(source,root);const run=a.store.sync.start('__all__',{readAll:true});a.store.sync.applyPage(run,[{aweme_id:'123',desc:'fixture',author:{nickname:'fixture'},video:{play_addr:{url_list:[]}}}],{next:'30',complete:false});a.store.sync.finish(run,false);a.store.save();a.store.setSetting('loggedOut',true);a.store.setSetting('authNeedsRefresh',true);await a.flush();await a.close();await a.open(root);
 assert.equal(a.store.syncProgress()[0].count,1);assert.equal(a.store.syncProgress()[0].canResume,true);assert.equal(a.store.getSetting('loggedOut'),true);assert.ok(a.store.file.startsWith(path.join(base,'a')));
 await b.open(root);assert.equal(b.writable,false);assert.equal(b.store.getSetting('loggedOut'),null);assert.equal(b.store.syncProgress().length,0);assert.equal(b.store.work('123').id,'123');assert.throws(()=>b.store.put('local_tags','123',{tags:['forbidden']}));
 }finally{await a.close();await b.close();source.close();assert.equal(path.dirname(base),os.tmpdir());fs.rmSync(base,{recursive:true,force:true,maxRetries:5,retryDelay:100});}
});
test('NAS download reuses its verified local fragment after pausing and reconnecting',async()=>{
 const base=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-upgrade-')),root=path.join(base,'share');fs.mkdirSync(root);const source=await Store.open(path.join(base,'source.sqlite'),path.join(base,'media')),nas=new NasLibrary(path.join(base,'profile'));const bytes=Buffer.from('verified-partial-media');source.upsertWork({aweme_id:'123',desc:'fixture',author:{nickname:'fixture'},video:{play_addr:{url_list:['https://v3.douyinvod.com/test.mp4']},origin_cover:{url_list:['https://p3.douyinpic.com/test.jpg']}}});
 try{await nas.migrate(source,root);const controller=new AbortController();let began;const started=new Promise(r=>{began=r;});const fetchMedia=async(url,options)=>{if(url.includes('.jpg'))return new Response('image',{headers:{'content-type':'image/jpeg'}});began();return new Response(new ReadableStream({start(c){c.enqueue(bytes.subarray(0,5));options.signal.addEventListener('abort',()=>c.error(Error('paused')),{once:true});}}),{headers:{'content-type':'video/mp4','content-length':String(bytes.length),etag:'"version-1"'}});};
 const task=nas.saveWork({id:'123'},controller.signal,{resolveWork:async()=>nas.store.work('123')},fetchMedia,()=>{});await started;await new Promise(r=>setTimeout(r,30));controller.abort();await assert.rejects(task);const staging=nas.status.staging;assert.ok(staging&&fs.existsSync(staging));await nas.close();await nas.open(root);let range;
 await nas.saveWork({id:'123'},new AbortController().signal,{resolveWork:async()=>nas.store.work('123')},async(url,options)=>{if(url.includes('.jpg'))return new Response('image',{headers:{'content-type':'image/jpeg'}});range=options.headers.Range;return new Response(bytes.subarray(5),{status:206,headers:{'content-type':'video/mp4','content-length':String(bytes.length-5),'content-range':`bytes 5-${bytes.length-1}/${bytes.length}`,etag:'"version-1"'}});},()=>{});
 assert.equal(range,'bytes=5-');const d=nas.store.download('123'),asset=d.assets.find(a=>a.key==='video');assert.deepEqual(fs.readFileSync(path.join(d.path,asset.file)),bytes);assert.equal(fs.existsSync(staging),false);
 }finally{await nas.close();source.close();assert.equal(path.dirname(base),os.tmpdir());fs.rmSync(base,{recursive:true,force:true,maxRetries:5,retryDelay:100});}
});
