import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {randomBytes,createHash} from 'node:crypto';
import {copyVerified} from '../electron/nas-transfer.mjs';import {Store} from '../electron/store.mjs';import {NasLibrary} from '../electron/nas-library.mjs';
function folder(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cangxia-transfer-'));t.after(()=>{assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:200});});return dir;}
test('NAS transfer reports copy and verification byte counts and verifies the hash',async t=>{const dir=folder(t),source=path.join(dir,'source'),dest=path.join(dir,'dest'),bytes=randomBytes(217054),events=[];fs.writeFileSync(source,bytes);const hash=await copyVerified(source,dest,{size:bytes.length,onProgress:p=>events.push(p)});assert.equal(hash,createHash('sha256').update(bytes).digest('hex'));for(const phase of ['copy','verify'])assert.ok(events.some(e=>e.phase===phase&&e.bytes===bytes.length));});
test('pause during NAS verification aborts without changing the local original',async t=>{const dir=folder(t),source=path.join(dir,'source'),dest=path.join(dir,'dest'),bytes=randomBytes(1000000),controller=new AbortController();fs.writeFileSync(source,bytes);await assert.rejects(copyVerified(source,dest,{signal:controller.signal,onProgress:p=>{if(p.phase==='verify')controller.abort();}}),/abort/i);assert.deepEqual(fs.readFileSync(source),bytes);});
test('a download batches source refresh with the final NAS record commit', {skip:process.platform!=='win32'},async t=>{
 const dir=folder(t),root=path.join(dir,'share');fs.mkdirSync(root);const source=await Store.open(path.join(dir,'db.sqlite'),path.join(dir,'media'));source.upsertWork({aweme_id:'123',desc:'fixture',author:{nickname:'test'},video:{play_addr:{url_list:['https://v3.douyinvod.com/fixture.mp4']},origin_cover:{url_list:['https://p3.douyinpic.com/fixture.jpg']}}});source.save();const nas=new NasLibrary(path.join(dir,'profile'));
 try{await nas.migrate(source,root);let commits=0;const original=nas.call.bind(nas);nas.call=(action,...args)=>{if(action==='commit')commits++;return original(action,...args);};
  await nas.saveWork({id:'123'},new AbortController().signal,{resolveWork:async()=>{nas.store.setSetting('sourceRefreshed',true);nas.store.save();await new Promise(r=>setTimeout(r,450));return nas.store.work('123');}},async url=>new Response(Buffer.from('fixture'),{headers:{'content-type':url.includes('mp4')?'video/mp4':'image/jpeg'}}),()=>{});
  assert.equal(commits,1);assert.equal(nas.store.isDownloaded('123'),true);
 }finally{await nas.close();source.close();}
});
test('NAS publication tolerates queued metadata saves and exposes progress', {skip:process.platform!=='win32',timeout:360000},async t=>{
 const dir=folder(t),share=process.env.CANGXIA_NAS_TRANSFER_TEST_ROOT,root=share?fs.mkdtempSync(path.join(share,'cangxia-owned-test-')):path.join(dir,'share');if(!share)fs.mkdirSync(root);
 const source=await Store.open(path.join(dir,'source.sqlite'),path.join(dir,'media'));source.upsertWork({aweme_id:'123',desc:'transfer fixture',author:{nickname:'test'},video:{play_addr:{url_list:[]}}});source.save();
 const nas=new NasLibrary(path.join(dir,'profile')),progress=[];const start=Date.now();
 try{await nas.migrate(source,root);const file=path.join(dir,'video.mp4');fs.writeFileSync(file,randomBytes(217054));nas.store.setSetting('syntheticFixture',randomBytes(2400000).toString('base64'));nas.store.save();
  await nas.uploadRecord({id:'123',state:'partial',assets:[{key:'video',file:'video.mp4',kind:'video',size:217054}]},dir,{onProgress:p=>{progress.push(p);if(share&&p.bytes===0)console.log({phase:p.phase,elapsedMs:Date.now()-start});}});
  assert.equal(nas.writable,true);assert.equal(nas.status.connected,true);assert.ok(nas.store.download('123'));assert.ok(progress.some(p=>p.phase==='copy'));assert.ok(progress.some(p=>p.phase==='verify'));assert.ok(progress.some(p=>p.phase==='records'));
  const controller=new AbortController();await assert.rejects(nas.uploadRecord({id:'123',state:'partial',assets:[{key:'video',file:'video.mp4',kind:'video',size:217054}]},dir,{signal:controller.signal,onProgress:()=>controller.abort()}));assert.ok(nas.store.download('123'),'aborting replacement retains the committed record');
  console.log({publicationElapsedMs:Date.now()-start,remote:!!share});
 }finally{await nas.close();source.close();if(share){assert.equal(path.dirname(root),path.resolve(share));assert.ok(path.basename(root).startsWith('cangxia-owned-test-'));fs.rmSync(root,{recursive:true,force:true,maxRetries:5,retryDelay:200});}}
});
