import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {Store} from '../electron/store.mjs';import {clearCollectionCheckpoints} from '../electron/collection-checkpoint-reset.mjs';
const raw=id=>({aweme_id:String(id),desc:'作品 '+id,author:{uid:'7',nickname:'作者',unique_id:'author'},video:{play_addr:{url_list:[]}}});
const page=(ids,next=null,complete=true)=>({items:ids.map(raw),next,complete});
async function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cx-read-history-'));let s=await Store.open(path.join(dir,'library.sqlite'),path.join(dir,'media'));s.setSetting('browserAccountKey','uid:1');t.after(async()=>{await s.fileStates.close();s.close();assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:100});});return {get s(){return s;},async reopen(){s.close();s=await Store.open(path.join(dir,'library.sqlite'),path.join(dir,'media'));return s;}};}
function full(s,ids){const run=s.collectionReads.start('__all__','full');s.collectionReads.apply(run,page(ids));return run;}
test('first read only stores a summary; front and middle discoveries retain unreturned historical records',async t=>{const {s}=await fixture(t);const initial=full(s,['1','2','3']);assert.equal(s.collectionReads.summary(initial).initialAdded,3);assert.equal(s.readHistory.items(initial.token).total,0);const next=full(s,['9','1','4','3']);const summary=s.collectionReads.summary(next);assert.deepEqual([summary.frontAdded,summary.filled,summary.existing,summary.notReturned,summary.historyCount],[1,1,2,1,5]);assert.deepEqual(s.orderedMemberRows('__all__').map(r=>r.work_id),['9','1','4','2','3']);assert.deepEqual(s.readHistory.items(next.token).items.map(i=>[i.id,i.kind]),[['9','front'],['4','fill']]);assert.equal(s.readHistory.runs().total,2);assert.ok(s.readHistory.stats().bytes<10000);});
test('previously missing historical work is logged once when it returns again without duplicating the library',async t=>{const {s}=await fixture(t);full(s,['1','2','3']);full(s,['1','3']);const returning=full(s,['1','2','3']);assert.equal(returning.added,0);assert.equal(returning.filled,1);assert.equal(returning.reappeared,1);const row=s.readHistory.items(returning.token).items[0];assert.equal(row.id,'2');assert.equal(row.reappeared,true);assert.equal(s.orderedMemberRows('__all__').length,3);const repeated=full(s,['1','2','3']);assert.equal(s.readHistory.items(repeated.token).total,0);});
test('pause, restart and resume preserve classification and a single log session',async t=>{const f=await fixture(t);full(f.s,['1','2','3']);let r=f.s.collectionReads,run=r.start('__all__','full');r.apply(run,page(['9','1'],'30',false));r.finish(run,'paused');const token=run.token;await f.reopen();r=f.s.collectionReads;run=r.start('__all__','full',{resume:true});r.apply(run,page(['1','4','3']));assert.equal(run.token,token);assert.equal(run.frontAdded,1);assert.equal(run.filled,1);assert.equal(f.s.readHistory.items(token).total,2);assert.equal(f.s.readHistory.runs().total,2);});
test('failed page rolls back both discoveries and their log entries; checkpoint reset preserves history logs',async t=>{const {s}=await fixture(t);full(s,['1','2']);const run=s.collectionReads.start('__all__','full');assert.throws(()=>s.collectionReads.apply(run,{items:[raw('9'),raw('bad')],next:'30',complete:false}));assert.equal(run.frontAdded,0);assert.equal(s.readHistory.items(run.token).total,0);assert.equal(s.work('9'),null);s.collectionReads.finish(run,'paused');clearCollectionCheckpoints(s);assert.equal(s.readHistory.runs().total,2);});
test('log pages are bounded and clearing logs leaves works, membership and read baselines intact',async t=>{const {s}=await fixture(t);full(s,['1','2']);const run=full(s,['1',...Array.from({length:120},(_,i)=>String(100+i)),'2']);assert.equal(s.readHistory.items(run.token).items.length,50);assert.equal(s.readHistory.items(run.token,{page:3}).items.length,20);const ids=s.orderedMemberRows('__all__').map(r=>r.work_id),base=s.collectionReads.baseline('__all__');s.readHistory.clear();assert.equal(s.readHistory.stats().runs,0);assert.deepEqual(s.orderedMemberRows('__all__').map(r=>r.work_id),ids);assert.deepEqual(s.collectionReads.baseline('__all__'),base);assert.ok(s.work('100'));});
test('author logs classify front and middle returns and remain independent of collection history',async t=>{const {s}=await fixture(t),id='MS4wLjABAAAA_READ_HISTORY_AUTHOR';s.authorSources.add(id,{user:{uid:'7',sec_uid:id,nickname:'作者',unique_id:'author'}});const authorRaw=value=>({...raw(value),author:{uid:'7',sec_uid:id,nickname:'作者'}});function authorRead(ids){const a=s.authorSources.start(id,{readAll:true});s.authorSources.apply(a,{items:ids.map(authorRaw),next:null,complete:true});return a;}const initial=authorRead(['1','2','3']);assert.equal(s.readHistory.items(initial.run.token).total,0);const second=authorRead(['9','1','4','3']),summary=s.authorSources.summary(second);assert.deepEqual([summary.frontAdded,summary.filled,summary.notReturned,summary.historyCount],[1,1,1,5]);assert.equal(s.readHistory.items(second.run.token).total,2);assert.equal(s.orderedMemberRows('__all__').length,0);const third=authorRead(['9','1','2','4','3']);assert.equal(third.run.reappeared,1);assert.equal(s.readHistory.items(third.run.token).items[0].id,'2');});
test('folder-only historical work remains pending when a complete total read never confirms its position',async t=>{const {s}=await fixture(t);s.discoverCollections([{collects_id:'77',collects_name:'夹'}]);s.setAdded(['77']);s.upsertWork(raw('1'));s.ingestMembers('77',['1'],true);full(s,['2']);assert.equal(s.orderedMemberRows('__all__').find(r=>r.work_id==='1').rank,null);assert.deepEqual(s.snapshot().pendingMembers.__all__,['1']);});
