import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../electron/store.mjs';import {selectWorks} from '../electron/filter.mjs';import {creatorIndex} from '../shared/creators.mjs';
const raw=(id,desc,uid='1')=>({aweme_id:id,desc,author:{uid,nickname:'同名作者',sec_uid:'MS4wLjAB'+uid.repeat(15)},images:[{url_list:['https://p3.douyinpic.com/fixture.png']}],cooperation_info:{co_creators:[{uid:'9',sec_uid:'MS4wLjAB'+('9'.repeat(15)),nickname:'共创作者',invite_status:1,role_title:'出镜'}]}});
async function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cx-search-')),store=await Store.open(path.join(dir,'library.sqlite'),path.join(dir,'media'));t.after(async()=>{await store.fileStates.close();store.close();assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:100});});store.upsertWork(raw('1','雷电将军 原比例 100% "原图" #cos'));store.upsertWork(raw('2','雷神 同一系列 #cos #fgo','2'));store.upsertWork(raw('3','其他作品 #fgo','3'));store.ingestMembers('__all__',['3','2','1'],true);store.put('local_tags','1',{id:'1',tags:['喜欢']});await store.lightViews.prepare();return store;}
test('indexed substring and identity filters match legacy results without changing source order',async t=>{
 const store=await fixture(t),ids=['3','2','1'];for(const options of [{query:'雷'},{query:'雷神'},{query:'雷电将军'},{query:'100%'},{query:'"原图"'},{query:'共创作者'},{tags:['cos']},{tags:['cos','fgo'],tagMode:'all'},{author:'uid:9'},{author:'uid:2'},{localTags:['喜欢']}]){
  const expected=selectWorks(ids.map(id=>({...store.work(id),localTags:store.get('local_tags',id)?.tags||[]})),{...options,creators:creatorIndex(store.creatorProfiles())}).map(w=>w.id);assert.deepEqual(await store.lightViews.search.query(ids,options),expected,JSON.stringify(options));
 }assert.equal(store.lightViews.search.fts,true);
});
test('editing and deleting tags update index entries; omitted list descriptions remain searchable',async t=>{const store=await fixture(t),ids=['1','2','3'];await store.lightViews.search.query(ids,{query:'原比例'});assert.equal(store.lightViews.view('1').description,undefined);store.put('works','1',{...store.work('1'),name:'changed',description:'新的描述'});assert.deepEqual(await store.lightViews.search.query(ids,{query:'原比例'}),[]);assert.deepEqual(await store.lightViews.search.query(ids,{query:'新的描述'}),['1']);store.put('local_tags','1',{id:'1',tags:[]});assert.deepEqual(await store.lightViews.search.query(ids,{localTags:['喜欢']}),[]);});
test('same nickname never merges distinct authors and refreshed creator handles are indexed',async t=>{const store=await fixture(t);assert.deepEqual(await store.lightViews.search.query(['3','2','1'],{author:'uid:1'}),['1']);store.rememberCreator({uid:'9',sec_uid:'MS4wLjAB'+('9'.repeat(15)),nickname:'共创作者',unique_id:'verified-handle'});assert.deepEqual(await store.lightViews.search.query(['3','2','1'],{query:'verified-handle'}),['3','2','1']);});
