const value=(v,max=240)=>v===undefined||v===null||v===0||v==='0'?'':String(v).trim().slice(0,max);
export const CREATOR_INFO_VERSION=2;
export function normalizeCreator(raw={}){return {uid:value(raw.uid||raw.user_id),secUid:value(raw.sec_uid||raw.secUid),uniqueId:value(raw.unique_id||raw.uniqueId)||value(raw.short_id||raw.shortId),nickname:value(raw.nickname||raw.name,120)||'未知作者',...(raw.role_title||raw.roleTitle?{roleTitle:value(raw.role_title||raw.roleTitle,100)}:{})};}
export function creatorKey(a){return a?.uid?'uid:'+a.uid:a?.secUid?'sec:'+a.secUid:a?.uniqueId?'handle:'+a.uniqueId:'';}
export function sameCreator(a,b){if(!a||!b)return false;if(a.uid&&b.uid&&a.uid!==b.uid)return false;if(a.secUid&&b.secUid&&a.secUid!==b.secUid)return false;return !!((a.uid&&a.uid===b.uid)||(a.secUid&&a.secUid===b.secUid));}
export function mergeCreator(old,next){old=normalizeCreator(old);next=normalizeCreator(next);if(creatorKey(old)&&creatorKey(next)&&!sameCreator(old,next))return next;const result={...old};for(const [key,v]of Object.entries(next))if(v&&v!=='未知作者')result[key]=v;return result;}
export function parseCoCreators(raw,primary){const rows=raw.cooperation_info?.co_creators;if(!Array.isArray(rows))return null;const result=[];for(const row of rows.slice(0,64)){if(row.invite_status!==undefined&&row.invite_status!==null&&Number(row.invite_status)!==1)continue;const creator=normalizeCreator(row);if(!creator.uid&&!creator.secUid||sameCreator(creator,primary))continue;const index=result.findIndex(a=>sameCreator(a,creator));if(index<0)result.push(creator);else result[index]=mergeCreator(result[index],creator);}return result;}
export function creatorIndex(profiles=[]){const map=new Map();for(const raw of profiles){const p={...normalizeCreator(raw),...(raw.fetchedAt?{fetchedAt:raw.fetchedAt}:{})};if(p.uid)map.set('uid:'+p.uid,p);if(p.secUid)map.set('sec:'+p.secUid,p);}return map;}
export function withCreatorProfile(person,index){const a=normalizeCreator(person),p=index?.get(a.uid?'uid:'+a.uid:'sec:'+a.secUid)||index?.get('sec:'+a.secUid);return p&&sameCreator(a,p)?{...mergeCreator(a,p),...(a.roleTitle?{roleTitle:a.roleTitle}:{})}:a;}
export function workCreators(work,index){const result=[];for(const raw of [work.author,...(work.coAuthors||[])]){const a=withCreatorProfile(raw,index);if(!result.some(b=>sameCreator(a,b)))result.push(a);}return result;}
export function matchesCreator(a,key){if(key.startsWith('uid:'))return a.uid===key.slice(4);if(key.startsWith('sec:'))return a.secUid===key.slice(4);if(key.startsWith('handle:'))return a.uniqueId===key.slice(7);return key===a.uid||key===a.secUid||key===a.uniqueId;}
