import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUp,Folder,FolderOpen,Monitor,Download,FileText,Image,Film,Music,HardDrive,FileJson,Plus,Search,Check,AlertCircle,LoaderCircle,ChevronRight} from 'lucide-react';
import './file-picker.css';
const icons={desktop:Monitor,downloads:Download,documents:FileText,pictures:Image,videos:Film,music:Music};
const equalPath=(a,b)=>a.replace(/[\\/]+$/,'').toLowerCase()===b.replace(/[\\/]+$/,'').toLowerCase();
function crumbs(value){if(!value)return [];const windows=value.includes('\\'),separator=windows?'\\':'/';let root,parts;if(value.startsWith('\\\\')){const all=value.slice(2).split('\\');root='\\\\'+all.splice(0,2).join('\\')+'\\';parts=all;}else if(windows){root=value.slice(0,3);parts=value.slice(3).split('\\');}else{root='/';parts=value.slice(1).split('/');}const result=[{name:root,path:root}];let current=root;for(const name of parts.filter(Boolean)){current+=(current.endsWith(separator)?'':separator)+name;result.push({name,path:current});}return result;}
const modified=value=>value?new Date(value).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'—';
export function FilePicker({api,mode,initial,onSelect,onCancel}){
 const [listing,setListing]=useState({path:'',parent:null,entries:[]}),[places,setPlaces]=useState([]),[disks,setDisks]=useState([]),[address,setAddress]=useState(''),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(true),[choosing,setChoosing]=useState(false),[query,setQuery]=useState(''),[newName,setNewName]=useState(''),[creating,setCreating]=useState(false),[history,setHistory]=useState({paths:[],index:-1});
 const generation=useRef(0),historyRef=useRef(history);
 async function load(dir,index=null){const key=++generation.current;setBusy(true);setError('');setSelected(null);setCreating(false);try{const r=await api.listDirectory(dir,mode);if(key!==generation.current)return;setListing(r);setAddress(r.path);setQuery('');const prior=historyRef.current;const next=index!==null?{...prior,index}:prior.paths[prior.index]===r.path?prior:{paths:[...prior.paths.slice(0,prior.index+1),r.path],index:prior.index+1};historyRef.current=next;setHistory(next);}catch(e){if(key===generation.current)setError('无法打开文件夹：'+e.message);}finally{if(key===generation.current)setBusy(false);}}
 useEffect(()=>{let active=true;(async()=>{try{const locations=await api.pickerLocations();if(!active)return;setPlaces(locations.shortcuts);await load(initial||locations.desktop);}catch(e){if(active){setError('无法打开默认目录：'+e.message);setBusy(false);}}})();api.listDirectory('',mode).then(r=>{if(active)setDisks(r.entries);}).catch(()=>{});return()=>{active=false;generation.current++;};},[]);
 async function choose(file){setChoosing(true);setBusy(true);setError('');try{await onSelect(file);}catch(e){setError(e.message);}finally{setBusy(false);setChoosing(false);}}
 const matches=listing.entries.filter(e=>e.name.toLowerCase().includes(query.toLowerCase()));
 const target=mode==='directory'?(selected?.directory?selected.path:listing.path):selected&&!selected.directory?selected.path:'';
 const pathCrumbs=crumbs(listing.path),shortcutIndex=pathCrumbs.findLastIndex(c=>places.some(p=>equalPath(p.path,c.path))),trail=pathCrumbs.slice(Math.max(0,shortcutIndex));
 const title=places.find(p=>equalPath(p.path,listing.path))?.name||crumbs(listing.path).at(-1)?.name||'此电脑';
 return <><div className="modal-content file-picker explorer-picker"><form className="path-navigation" onSubmit={e=>{e.preventDefault();load(address);}}><button type="button" aria-label="后退" disabled={busy||history.index<=0} onClick={()=>load(history.paths[history.index-1],history.index-1)}><ArrowLeft size={17}/></button><button type="button" aria-label="前进" disabled={busy||history.index>=history.paths.length-1} onClick={()=>load(history.paths[history.index+1],history.index+1)}><ArrowRight size={17}/></button><button type="button" aria-label="上一级目录" disabled={busy||listing.parent===null} onClick={()=>load(listing.parent)}><ArrowUp size={17}/></button><div className="picker-address"><FolderOpen size={16}/><input aria-label="文件夹路径" value={address} placeholder="输入完整路径，按回车打开" onChange={e=>setAddress(e.target.value)}/></div><button type="submit" disabled={busy}>前往</button></form>
 <div className="picker-browser"><nav className="picker-sidebar" aria-label="常用位置"><small>常用位置</small>{places.map(p=>{const Icon=icons[p.id]||Folder;return <button type="button" key={p.id} disabled={busy} className={equalPath(listing.path,p.path)?'active':''} onClick={()=>load(p.path)} title={p.path}><Icon size={16}/>{p.name}</button>;})}<small>此电脑</small><button type="button" disabled={busy} className={!listing.path?'active':''} onClick={()=>load('')}><Monitor size={16}/>此电脑</button>{disks.map(d=><button type="button" key={d.path} disabled={busy} className={equalPath(d.path,listing.path)?'active':''} onClick={()=>load(d.path)}><HardDrive size={16}/>{d.name}</button>)}</nav>
 <div className="picker-main"><div className="picker-breadcrumb" aria-label="当前位置"><button disabled={busy} onClick={()=>load('')}>此电脑</button>{trail.map(c=><React.Fragment key={c.path}><ChevronRight size={12}/><button disabled={busy} title={c.path} onClick={()=>load(c.path)}>{places.find(p=>equalPath(p.path,c.path))?.name||c.name}</button></React.Fragment>)}</div>
 <div className="file-toolbar"><div className="choice-search-wrap"><Search size={15}/><input aria-label="搜索文件夹或文件" value={query} onChange={e=>{setQuery(e.target.value);setSelected(null);}} placeholder={`搜索${title}`}/></div><button className="text-button" disabled={busy||!listing.path} onClick={()=>setCreating(!creating)}><Plus size={14}/>新建文件夹</button></div>
 {creating&&<form className="new-folder" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const dir=await api.makeDirectory(listing.path,newName);setNewName('');await load(dir);}catch(e){setError(e.message);}finally{setBusy(false);}}}><input autoFocus aria-label="新文件夹名称" value={newName} onChange={e=>setNewName(e.target.value)} placeholder="文件夹名称" maxLength={100}/><button className="button secondary" disabled={busy||!newName.trim()}>创建</button></form>}
 {error&&<div className="invalid-note" role="alert"><AlertCircle size={16}/>{error}</div>}
 <div className="picker-table-head"><span>名称</span><span>修改时间</span><span>类型</span></div><div className="file-entries" aria-busy={busy} aria-label="文件夹内容">{busy?<div className="picker-placeholder" role="status"><LoaderCircle size={23} className="spin"/><span>正在打开文件夹…</span></div>:matches.map(e=><button type="button" key={e.path} className={selected?.path===e.path?'selected':''} aria-pressed={selected?.path===e.path} aria-label={`${e.directory?'文件夹':'文件'} ${e.name}`} onClick={()=>setSelected(e)} onDoubleClick={()=>e.directory?load(e.path):choose(e.path)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();e.directory?load(e.path):choose(e.path);}}}><span className="picker-file-name">{e.directory?<Folder size={19}/>:<FileJson size={19}/>}<span>{e.name}</span>{selected?.path===e.path&&<Check size={13}/>}</span><span className="picker-date">{modified(e.modified)}</span><span className="picker-file-type">{e.directory?'文件夹':'JSON 文件'}</span></button>)}{!busy&&!matches.length&&<div className="picker-placeholder"><FolderOpen size={30}/><strong>{query?'没有匹配的项目':listing.path?'这个文件夹中没有可选项目':'没有可用磁盘'}</strong><span>{query?'试试其他名称':listing.path?'可以使用当前目录，或新建一个文件夹':'可在上方输入完整路径打开'}</span></div>}</div><div className="picker-list-foot"><span>{matches.length} 个项目</span><span>单击选择 · 双击或按 Enter 打开</span></div></div></div>
 <div className="picker-selected"><FolderOpen size={16}/><span>{mode==='directory'?'选择的文件夹':'选择的文件'}<strong>{target||'请选择'}</strong></span></div></div><footer className="modal-footer"><button className="button secondary" disabled={choosing} onClick={onCancel}>取消</button><button className="button primary" disabled={busy||!target} onClick={()=>choose(target)}>{busy?'正在处理…':mode==='directory'?'使用此目录':'导入文件'}</button></footer></>;
}
