import React,{useState} from 'react';
import {FolderOpen,Download,Pause,Play,RefreshCw,X,Check,Image,Info} from 'lucide-react';
import './flat-download.css';

export function FlatDownloadSetup({count,directory,includeCover,onCover,onChoose,onStart,onCancel,busy}){
 return <><div className="modal-content flat-setup"><div className="flat-intro"><span><Download size={23}/></span><div><strong>只带走喜欢的图片和视频</strong><p>已选择 {count} 个作品 · 按当前列表顺序命名</p></div></div><label>本次保存到</label><button className="flat-directory" onClick={onChoose} disabled={busy}><FolderOpen size={19}/><span>{directory||'选择一个文件夹'}</span><small>选择目录</small></button><label className="flat-checkbox"><input type="checkbox" checked={includeCover} onChange={e=>onCover(e.target.checked)} disabled={busy}/><span>同时下载视频封面<small>图文作品始终保存全部图片</small></span></label><div className="flat-note"><Info size={17}/><p>所有媒体平铺在这个文件夹，不保存作品信息。<br/>不加入本地媒体库，不改变“已下载”标记。任务仅在本次运行中保留，退出后不再续传。</p></div></div><footer className="modal-footer"><button className="button secondary" disabled={busy} onClick={onCancel}>取消</button><button className="button primary" disabled={busy||!directory||!count} onClick={onStart}><Download size={16}/>{busy?'正在检查…':'开始单独下载'}</button></footer></>;
}
export function FlatDownloadManager({queue,onAction,busy}){
 const [cancelId,setCancelId]=useState(null),[expanded,setExpanded]=useState({}),[limits,setLimits]=useState({});const batches=queue?.batches||[];
 return <div className="modal-content flat-manager"><p className="muted small">仅显示本次运行的任务。取消会保留完整文件，并清理未完成片段。</p>{!batches.length&&<div className="flat-empty"><Image size={30}/><strong>暂无单独下载</strong><span>选择作品后，点击“单独下载”即可开始</span></div>}
 {batches.map((b,i)=>{const remaining=b.jobs.some(j=>['waiting','running'].includes(j.state)),active=remaining||b.failed>0;return <section className="flat-batch" key={b.id}><header><div><strong>第 {i+1} 批 · {b.total} 个作品</strong><button className="flat-path" title={b.directory} onClick={()=>onAction('flatOpen',b.id)}><FolderOpen size={13}/>{b.directory}</button></div><span className={`flat-badge ${b.complete===b.total?'done':''}`}>{b.canceled?'已取消':b.complete===b.total?'已完成':b.paused?'已暂停':remaining?'进行中':'有失败'}</span></header><div className="flat-stats"><span><b>{b.complete}</b> 已完成</span><span><b>{b.failed}</b> 失败</span><span><b>{b.files}</b> 文件就绪</span></div><div className="progress" role="progressbar" aria-label={`第 ${i+1} 批下载进度`} aria-valuemin={0} aria-valuemax={b.total} aria-valuenow={b.complete}><span style={{width:`${b.total?100*b.complete/b.total:0}%`}}/></div>{b.skipped>0&&<small className="muted">其中 {b.skipped} 个文件与目录中的完整文件一致，已跳过</small>}{b.cleanupMessage&&<p className="muted small" role="alert">{b.cleanupMessage}</p>}<div className="flat-actions">{!b.canceled&&remaining&&<button className="button secondary" disabled={busy} onClick={()=>onAction(b.paused?'flatResume':'flatPause',b.id)}>{b.paused?<Play size={14}/>:<Pause size={14}/>}{b.paused?'继续':'暂停'}</button>}{!b.canceled&&b.failed>0&&<button className="button secondary" disabled={busy} onClick={()=>onAction('flatRetry',b.id)}><RefreshCw size={14}/>重试失败</button>}{!b.canceled&&active?<button className="text-button" disabled={busy} onClick={()=>setCancelId(b.id)}>取消本批</button>:<button className="text-button" disabled={busy} onClick={()=>onAction('flatClear',b.id)}>清除列表</button>}</div>{cancelId===b.id&&<div className="flat-cancel" role="alert"><p>取消剩余任务？已保存的完整文件会保留。</p><button className="button secondary" onClick={()=>setCancelId(null)}>继续保留</button><button className="button danger" disabled={busy} onClick={async()=>{await onAction('flatCancel',b.id);setCancelId(null);}}>取消剩余任务</button></div>}<details className="flat-jobs" onToggle={e=>{const open=e.currentTarget.open;setExpanded(old=>({...old,[b.id]:open}));}}><summary>查看任务 · {b.jobs.length}</summary>{expanded[b.id]&&b.jobs.slice(0,limits[b.id]||50).map(j=><div className="job" key={j.id}>{j.state==='complete'?<Check size={15}/>:j.state==='canceled'?<X size={15}/>:<Download size={15}/>}<div className="job-body"><strong>{j.title}</strong><small>{{complete:'已完成',running:'正在保存',waiting:b.paused?'已暂停':'等待中',failed:'未完成',canceled:'已取消'}[j.state]}{j.total?` · ${j.done}/${j.total} 个文件`:''}{j.message?` · ${j.message}`:''}</small></div></div>)}{expanded[b.id]&&b.jobs.length>(limits[b.id]||50)&&<button className="text-button" onClick={()=>setLimits(old=>({...old,[b.id]:(old[b.id]||50)+50}))}>再显示 50 个任务</button>}</details></section>;})}</div>;
}
