import React from 'react';
import {Archive,Cloud,Folder,Heart,Info,Search,Users,HardDrive} from 'lucide-react';
import './nas-ui.css';
const fmt=n=>Number(n||0).toLocaleString('zh-CN');
const bytes=n=>n>=1073741824?`${(n/1073741824).toFixed(1)} GB`:`${(n/1048576).toFixed(1)} MB`;
export function NASTabs({tab,library,onChange}){
 return <div className="nas-classification"><div className="nas-tabs" role="tablist" aria-label="NAS 备份分类">{[['all','全部备份',Archive],['collection','收藏备份',Heart],['author','作者备份',Users]].map(([id,label,Icon])=><button type="button" key={id} id={'nas-tab-'+id} role="tab" aria-selected={tab===id} aria-controls="nas-work-panel" onClick={()=>onChange(id)}><Icon size={17}/><span>{label}</span><small>{fmt(library.counts[id])}</small></button>)}</div><p className="nas-count-note"><Info size={13}/>同一作品可出现在多个分类，全部备份只计一次</p></div>;
}
export function NASSidebar({tab,library,collection,author,query,setQuery,onCollection,onAuthor}){
 if(tab==='all')return <section className="nas-context nas-overview" aria-label="备份概况"><h3>备份概况</h3>{[[Archive,'作品总数',fmt(library.counts.all)],[Heart,'收藏关联',fmt(library.counts.collection)],[Users,'作者关联',fmt(library.counts.author)],[HardDrive,'媒体大小',bytes(library.bytes)]].map(([Icon,label,value])=><div key={label}><Icon size={17}/><span>{label}</span><strong>{value}</strong></div>)}</section>;
 if(tab==='collection')return <nav className="nas-context nas-context-nav" aria-label="NAS 收藏夹"><h3>收藏夹</h3><button className={`collection-nav ${!collection||collection==='__all__'?'chosen':''}`} onClick={()=>onCollection('')}><Heart size={18}/><span>收藏</span><small>{fmt(library.counts.collection)}</small></button><h3>自建收藏夹</h3><div className="nas-context-scroll">{library.collections.map(c=><button key={c.id} aria-label={`NAS 收藏夹 ${c.name}`} className={`collection-nav ${collection===c.id?'chosen':''}`} onClick={()=>onCollection(c.id)} title={c.name}><Folder size={17}/><span>{c.name}</span><small>{fmt(c.count)}</small>{c.removed&&<em>已移除</em>}</button>)}{!library.collections.length&&<p className="nas-sidebar-note">自建收藏夹有媒体备份后显示在这里</p>}</div></nav>;
 const authors=library.authors.filter(a=>(a.name+' '+a.uniqueId+' '+a.id).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 return <nav className="nas-context nas-context-nav" aria-label="NAS 备份作者"><h3>备份作者</h3><label className="nas-author-search"><Search size={14}/><input aria-label="搜索备份作者" placeholder="搜索作者" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className={`collection-nav ${!author?'chosen':''}`} onClick={()=>onAuthor('')}><Users size={17}/><span>所有作者</span><small>{fmt(library.counts.author)}</small></button><div className="nas-context-scroll">{authors.map(a=><button key={a.id} aria-label={`NAS 作者 ${a.name}`} className={`collection-nav ${author===a.id?'chosen':''}`} onClick={()=>onAuthor(a.id)} title={`${a.name} · ${a.uniqueId||a.id}`}><span className="nas-author-avatar">{a.name.slice(0,1)}</span><span>{a.name}</span><small>{fmt(a.count)}</small>{a.removed&&<em>已移除</em>}</button>)}{!authors.length&&<p className="nas-sidebar-note">{query?'没有匹配的备份作者':'作者作品有媒体备份后显示在这里'}</p>}</div>{library.authors.some(a=>a.removed)&&<p className="nas-sidebar-note"><Info size={13}/>已移除作者的备份仍可查看</p>}</nav>;
}
export function NASSourceBadge({id,library}){const collection=library.collectionAll.has(id),author=library.authorAll.has(id);return <span className="nas-source-badge">{collection&&author?'收藏 · 作者':author?'作者':collection?'收藏':'已保留'}</span>;}
