import React,{useEffect,useState} from 'react';
import {Info,ExternalLink,ArrowLeft,ArrowRight,Trash2} from 'lucide-react';
import './read-history.css';
const number=value=>Number(value||0).toLocaleString('zh-CN');
const date=value=>value?new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'时间未记录';
export function ReadSummary({summary,onClose,onLogs}){
 const s=summary;const label=s.source==='author'?(s.mode==='full'?'完整读取':'限定读取'):(s.mode==='full'?'完整核对':'检查新增');return <><div className="modal-content read-result"><h3>{s.saveFailed?'读取内容已保留，收尾保存待检查':s.status==='complete'?'本轮读取完成':s.outcome==='limit'?'本段读取完成':'本轮读取已停止'}</h3><p>{s.name} · {label} · {date(s.startedAt)}</p><div className="read-result-counts"><div><strong>{number(s.checked)}</strong>本轮取得</div><div><strong>{s.frontAdded===null?'未区分':number(s.frontAdded)}</strong>前面新增</div><div><strong>{s.filled===null?'未区分':number(s.filled)}</strong>补齐记录</div><div><strong>{number(s.existing)}</strong>已有记录返回</div></div>{s.initialAdded>0&&<p>首次读入 {number(s.initialAdded)} 条记录，建立历史对照；本轮仅保存总结。</p>}{s.reappeared>0&&<p>补齐记录中有 {number(s.reappeared)} 条是历史作品本轮重新返回。</p>}<div className="info-box"><Info size={17}/><p>{s.notReturned===null?'本轮没有全量核对历史，未检查的记录继续保留。':`历史记录中本轮未返回 ${number(s.notReturned)} 条，全部保留。`}<br/>当前累计保留 {number(s.historyCount)} 条历史记录。补齐记录不自动下载媒体。</p></div>{s.warning&&<p className="muted">本轮返回数量明显减少，已保留历史记录及原有对照，可稍后再核对。</p>}{s.legacy&&<p className="muted">旧版本只保留了读取摘要，无法补回当时未记录的差异详情。</p>}<p className="muted small">{s.message||s.reason}</p></div><footer className="modal-footer"><button className="button secondary" onClick={onLogs}>查看读取日志</button><button className="button primary" onClick={onClose}>完成</button></footer></>;
}
function Pages({page,pages,onChange}){return <nav className="pagination" aria-label="读取日志分页"><button disabled={page<=1} onClick={()=>onChange(page-1)}><ArrowLeft size={14}/>上一页</button><span>每页 50 条 · {page} / {pages}</span><button disabled={page>=pages} onClick={()=>onChange(page+1)}>下一页<ArrowRight size={14}/></button></nav>;}
export function ReadHistoryPanel({api,onWork,onOriginal,onClose}){
 const [runs,setRuns]=useState(null),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[details,setDetails]=useState(null),[detailPage,setDetailPage]=useState(1),[kind,setKind]=useState('all'),[error,setError]=useState(''),[epoch,setEpoch]=useState(0),[clearing,setClearing]=useState(false),[confirmClear,setConfirmClear]=useState(false);
 useEffect(()=>{let active=true;setError('');setRuns(null);api.readHistoryRuns({page}).then(value=>{if(active)setRuns(value);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[page,epoch]);
 useEffect(()=>{let active=true;setDetails(null);setError('');if(selected)api.readHistoryItems(selected.token,{page:detailPage,kind}).then(value=>{if(active)setDetails(value);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[selected?.token,detailPage,kind,epoch]);
 async function clear(){setClearing(true);try{await api.clearReadHistory();setConfirmClear(false);setSelected(null);setPage(1);setEpoch(n=>n+1);}catch(e){setError(e.message);}finally{setClearing(false);}}
 if(confirmClear)return <><div className="modal-content"><h3>清空本机读取日志？</h3><p>只删除读取总结和日志中的差异作品信息。作品记录、本地文件、NAS 副本及读取对照保留。</p><p className="muted small">释放的数据库空间会供后续数据复用，不执行整库压缩。</p>{error&&<p role="alert">{error}</p>}</div><footer className="modal-footer"><button className="button secondary" disabled={clearing} onClick={()=>setConfirmClear(false)}>取消</button><button className="button danger" disabled={clearing} onClick={clear}>{clearing?'正在清理…':'确认清空读取日志'}</button></footer></>;
 if(selected)return <><div className="modal-content"><button className="text-button" onClick={()=>setSelected(null)}><ArrowLeft size={14}/>返回全部日志</button><h3>{selected.name} · {date(selected.startedAt)}</h3><p>前面新增 {selected.frontAdded===null?'旧版未区分':number(selected.frontAdded)} · 补齐记录 {selected.filled===null?'旧版未区分':number(selected.filled)} · 本轮取得 {number(selected.checked)}</p><div className="read-log-tabs">{[['all','全部差异'],['front','前面新增'],['fill','补齐记录']].map(([key,label])=><button key={key} className={`button secondary ${kind===key?'active':''}`} onClick={()=>{setKind(key);setDetailPage(1);}}>{label}</button>)}</div>{!details?<p role="status">正在读取日志…</p>:<>{!details.total&&<p className="muted">{selected.legacy?'旧版本没有保存差异作品详情。':selected.initialAdded?'首次读取只保存总结，未逐条复制全部作品信息。':'这轮没有此类差异作品。'}</p>}<div className="read-log-items">{details.items.map(w=><article key={w.id}><button className="text-button" onClick={()=>onWork(w.id)}>{w.name||w.id}</button><small>{w.type==='video'?'视频':'图文'} · {w.kind==='front'?'前面新增':w.reappeared?'历史作品重新返回':'补齐记录'} · 本轮位置 {w.position+1}</small><p>发布作者：{w.author?.nickname}{w.author?.uniqueId?` · 抖音号 ${w.author.uniqueId}`:''}</p><small>作品 ID：{w.id}</small>{w.foundAt&&<small>取得时间：{date(w.foundAt)}</small>}<button className="text-button" onClick={()=>onOriginal(w.id)}><ExternalLink size={13}/>打开抖音作品</button></article>)}</div><Pages page={details.page} pages={details.pages} onChange={setDetailPage}/></>}{error&&<p role="alert">{error}</p>}</div><footer className="modal-footer"><button className="button secondary" onClick={onClose}>关闭</button></footer></>;
 return <><div className="modal-content"><p className="muted small">本机账号收藏、自建收藏夹和作者作品的所有读取日志。仅记录差异作品的基本信息，不复制封面、视频或完整作品数据。</p>{runs&&<p>{number(runs.stats.runs)} 轮 · {number(runs.stats.items)} 条差异详情 · 日志文本约 {(runs.stats.bytes/1024).toFixed(1)} KB（不含索引和空闲页）</p>}{!runs?<p role="status">正在读取日志…</p>:<>{!runs.total&&<p className="muted">暂无读取日志。下一次读取结束后会在这里保存总结。</p>}<div className="read-log-runs">{runs.items.map(s=><button key={s.token} onClick={()=>{setSelected(s);setDetailPage(1);setKind('all');}}><strong>{s.name} · {s.source==='author'?(s.mode==='full'?'作者完整读取':'作者限定读取'):(s.mode==='full'?'完整核对':'检查新增')}</strong><small>{date(s.startedAt)} · {s.status==='complete'?'已完成':s.status==='running'?'读取中':'已停止'}</small><span>取得 {number(s.checked)} · 前面新增 {s.frontAdded===null?'旧版未区分':number(s.frontAdded)} · 补齐 {s.filled===null?'旧版未区分':number(s.filled)}</span></button>)}</div><Pages page={runs.page} pages={runs.pages} onChange={setPage}/></>}{error&&<p role="alert">{error}</p>}</div><footer className="modal-footer"><button className="button danger" disabled={!runs?.total} onClick={()=>setConfirmClear(true)}><Trash2 size={14}/>清空读取日志</button><button className="button secondary" onClick={onClose}>关闭</button></footer></>;
}
