import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUp,Folder,FileJson,Plus,Search,Check,Info,X,Trash2,CheckCircle,AlertCircle} from 'lucide-react';

export function Pagination({page,pages,onChange,location}){
 return <nav className="pagination" aria-label={`${location}分页`}><span>每页 20 个</span><button aria-label={`${location}上一页`} disabled={page<=1} onClick={()=>onChange(page-1)}><ArrowLeft size={15}/></button><strong>{page}<em>/ {pages}</em></strong><button aria-label={`${location}下一页`} disabled={page>=pages} onClick={()=>onChange(page+1)}><ArrowRight size={15}/></button></nav>;
}
export function Toast({message,onClose}){
 const [center,setCenter]=useState('50%');
 useLayoutEffect(()=>{
  const update=()=>{const modals=[...document.querySelectorAll('.modal')];const anchor=modals.at(-1)||document.querySelector('.main-content');if(anchor){const r=anchor.getBoundingClientRect();setCenter(`${r.left+r.width/2}px`);}};
  update();const ro=new ResizeObserver(update);ro.observe(document.body);const observer=new MutationObserver(update);observer.observe(document.getElementById('root'),{childList:true,subtree:true});window.addEventListener('resize',update);
  return()=>{ro.disconnect();observer.disconnect();window.removeEventListener('resize',update);};
 },[]);
 return <div className="toast" role="status" style={{left:center}}><Info size={17}/><span>{message}</span><button aria-label="关闭提示" onClick={onClose}><X size={15}/></button></div>;
}
export function FilePicker({api,mode,initial,onSelect,onCancel}){
 const [listing,setListing]=useState({path:'',parent:null,entries:[]}),[address,setAddress]=useState(initial||''),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[newName,setNewName]=useState(''),[creating,setCreating]=useState(false);
 const generation=useRef(0);
 async function load(dir){const key=++generation.current;setBusy(true);setError('');setSelected('');try{const r=await api.listDirectory(dir,mode);if(key!==generation.current)return;setListing(r);setAddress(r.path);setQuery('');}catch(e){if(key===generation.current)setError('无法打开文件夹：'+e.message);}finally{if(key===generation.current)setBusy(false);}}
 useEffect(()=>{load(initial||'');return()=>{generation.current++;};},[]);
 async function choose(file){setBusy(true);setError('');try{await onSelect(file);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><div className="modal-content file-picker"><form className="path-navigation" onSubmit={e=>{e.preventDefault();load(address);}}><button type="button" title="此电脑" disabled={busy} onClick={()=>load('')}><Folder size={18}/></button><button type="button" aria-label="上一级目录" disabled={busy||listing.parent===null} onClick={()=>load(listing.parent)}><ArrowUp size={17}/></button><input aria-label="文件夹路径" value={address} placeholder="输入完整路径，按回车打开" onChange={e=>setAddress(e.target.value)}/><button disabled={busy}>前往</button></form><div className="file-toolbar"><div className="choice-search-wrap"><Search size={15}/><input aria-label="搜索文件夹或文件" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索当前目录"/></div><button className="text-button" disabled={busy||!listing.path} onClick={()=>setCreating(!creating)}><Plus size={14}/>新建文件夹</button></div>{creating&&<form className="new-folder" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const dir=await api.makeDirectory(listing.path,newName);setCreating(false);setNewName('');await load(dir);}catch(e){setError(e.message);}finally{setBusy(false);}}}><input autoFocus aria-label="新文件夹名称" value={newName} onChange={e=>setNewName(e.target.value)} placeholder="文件夹名称" maxLength={100}/><button className="button secondary" disabled={busy||!newName}>创建</button></form>}{error&&<div className="invalid-note" role="alert"><AlertCircle size={16}/>{error}</div>}<div className="file-entries" aria-busy={busy}>{listing.entries.filter(e=>e.name.toLowerCase().includes(query.toLowerCase())).map(e=><button key={e.path} disabled={busy} className={selected===e.path?'selected':''} onClick={()=>e.directory?load(e.path):setSelected(e.path)} onDoubleClick={()=>{if(!e.directory)choose(e.path);}}>{e.directory?<Folder size={20}/>:<FileJson size={20}/>}<span>{e.name}</span>{selected===e.path&&<Check size={16}/>}</button>)}{!listing.entries.length&&!busy&&<p className="muted">{listing.path?'此目录没有可选择的项目':'没有可用磁盘，可输入完整路径访问共享目录。'}</p>}</div><p className="picker-selected">{mode==='directory'?`将使用当前目录：${listing.path||'请选择文件夹'}`:`已选择：${selected||'请选择 JSON 文件'}`}</p></div><footer className="modal-footer"><button className="button secondary" disabled={busy} onClick={onCancel}>取消</button><button className="button primary" disabled={busy||!(mode==='directory'?listing.path:selected)} onClick={()=>choose(mode==='directory'?listing.path:selected)}>{busy?'正在处理…':mode==='directory'?'使用此目录':'导入文件'}</button></footer></>;
}
export function DeleteConfirmation({intent,onConfirm,onCancel,busy}){
 const local=intent.kind==='local';
 return <><div className="modal-content confirm-content"><div className={`confirm-symbol ${local?'danger':''}`}><Trash2 size={26}/></div><h3>{local?`删除 ${intent.count} 个作品的本地文件？`:`删除 ${intent.count} 个作品的读取记录？`}</h3><p>{local?(intent.backup?'本机的视频、图片和作品信息会移入系统回收站。NAS 已有的备份副本保留。':'视频、图片和作品信息会移入系统回收站，并撤销已下载标记。抖音账号收藏不受影响。'):'作品会从软件的总收藏与自建收藏夹读取列表中一起移除。抖音收藏、本地文件、标签及本地排序保留。之后重新读取可以恢复。'}</p>{local&&intent.invalid&&<div className="invalid-note"><AlertCircle size={18}/>原作品已失效，删除后将无法从抖音重新下载。</div>}</div><footer className="modal-footer"><button className="button secondary" disabled={busy} onClick={onCancel}>取消</button><button className="button danger solid" disabled={busy||!intent.count} onClick={onConfirm}>{busy?'正在删除…':local?'删除本地文件':'删除读取记录'}</button></footer></>;
}
export function RepairReport({report,onStart,busy,onClose}){
 return <><div className="modal-content"><div className="repair-summary"><span><CheckCircle size={18}/><b>{report.complete}</b>完整</span><span><Info size={18}/><b>{report.missing}</b>需要补齐</span><span><AlertCircle size={18}/><b>{report.errors}</b>无法检查</span></div>{!report.missing&&!report.errors&&<div className="complete-message"><CheckCircle size={34}/><h3>文件完整，无需补齐</h3><p>未添加任何下载任务。</p></div>}<div className="repair-list">{report.items.filter(i=>i.status!=='complete').map(i=><article key={i.id}><strong>{i.name}</strong><p>{i.status==='error'?`无法检查：${i.error}`:i.missing.map(m=>`${m.label}（${m.reason}）`).join('、')}</p></article>)}</div>{report.errors>0&&<p className="muted">无法检查的作品不会加入补齐任务。请检查磁盘连接或访问权限后重试。</p>}</div><footer className="modal-footer"><button className="button secondary" disabled={busy} onClick={onClose}>关闭</button>{report.missing>0&&<button className="button primary" disabled={busy} onClick={onStart}>{busy?'正在确认…':`开始补齐 ${report.missing} 个作品`}</button>}</footer></>;
}
